#!/usr/bin/env python3
"""
Turkish ASCII-to-Unicode normalizer for Pterodactyl egg translations.
Converts ASCII-Turkish text (no diacritics) to proper Turkish Unicode (ğ, ş, ı, ç, ö, ü).
"""

import json
import os
import re

# ============================================================================
# Comprehensive Turkish word normalization map
# ASCII-Turkish word → Proper Turkish Unicode word
# ============================================================================

TR_WORD_MAP = {
    # ---- Noun suffixes: -i/-ı/-u/-ü (possessive/accusative) ----
    "Adi": "Adı",
    "Adres": "Adres",
    "Adresi": "Adresi",
    "Anahtari": "Anahtarı",
    "Araligi": "Aralığı",
    "Baglantisi": "Bağlantısı",
    "Binary'si": "Binary'si",
    "Bolgesi": "Bölgesi",
    "Boyutu": "Boyutu",
    "Carpma": "Çarpma",
    "Carpani": "Çarpanı",
    "Ciktisini": "Çıktısını",
    "Dali": "Dalı",
    "Derlemesi": "Derlemesi",
    "Dili": "Dili",
    "Dizesi": "Dizesi",
    "Dosyasi": "Dosyası",
    "Dosyalarini": "Dosyalarını",
    "Esigi": "Eşiği",
    "Hafizasi": "Hafızası",
    "Haritasi": "Haritası",
    "Hatti": "Hattı",
    "Icerigini": "İçeriğini",
    "ID'si": "ID'si",
    "IP'si": "IP'si",
    "Isigi": "Işığı",
    "Kalesi": "Kalesi",
    "Kalitesi": "Kalitesi",
    "Kanali": "Kanalı",
    "Kimligi": "Kimliği",
    "Klasoru": "Klasörü",
    "Kodu": "Kodu",
    "Koleksiyonu": "Koleksiyonu",
    "Korumasi": "Koruması",
    "Kurallari": "Kuralları",
    "Limiti": "Limiti",
    "Listesi": "Listesi",
    "Mesafesi": "Mesafesi",
    "Metni": "Metni",
    "Modlari": "Modları",
    "Modu": "Modu",
    "Numarasi": "Numarası",
    "Olusumu": "Oluşumu",
    "Onbellegini": "Önbellegini",
    "Paketi": "Paketi",
    "Parametreleri": "Parametreleri",
    "Platformu": "Platformu",
    "Portu": "Portu",
    "Sifresi": "Şifresi",
    "Suresi": "Süresi",
    "Surumu": "Sürümü",
    "Surumunu": "Sürümünü",
    "Tarafi": "Tarafı",
    "Temizle": "Temizle",
    "Tipi": "Tipi",
    "Tohumu": "Tohumu",
    "Turu": "Türü",
    "URL'si": "URL'si",
    "Yapilandirmasi": "Yapılandırması",
    "Yolu": "Yolu",
    "Yukleyici": "Yükleyici",
    "Yukleyicisi": "Yükleyicisi",
    "Yuksekligi": "Yüksekliği",
    "Yuvasi": "Yuvası",

    # ---- Words with ş (s-with-cedilla) ----
    "Baslangic": "Başlangıç",
    "Baslangicta": "Başlangıçta",
    "Baslatma": "Başlatma",
    "Dogmasini": "Doğmasını",
    "Eslesme": "Eşleşme",
    "Etkinlestir": "Etkinleştir",
    "Etkinlestirme": "Etkinleştirme",
    "Gecersiz": "Geçersiz",
    "Giris": "Giriş",
    "Goster": "Göster",
    "Gorunur": "Görünür",
    "Gorus": "Görüş",
    "Guvenli": "Güvenli",
    "Guvensiz": "Güvensiz",
    "Hilelere": "Hilelere",
    "Insa": "İnşa",
    "Istemci": "İstemci",
    "Kisi": "Kişi",
    "Kisisel": "Kişisel",
    "Kullanilabilir": "Kullanılabilir",
    "Kullanicisi": "Kullanıcısı",
    "Nisangahi": "Nişangahı",
    "Olusturma": "Oluşturma",
    "Oyunculu": "Oyuncu",
    "Sifre": "Şifre",
    "Sifresi": "Şifresi",
    "Sikistirma": "Sıkıştırma",
    "Tasi": "Taşı",
    "Ucusa": "Uçuşa",
    "Varlik": "Varlık",
    "Yapilandir": "Yapılandır",
    "Yapilandirma": "Yapılandırma",
    "Yeniden": "Yeniden",
    "Yonetici": "Yönetici",
    "Yonlendirme": "Yönlendirme",
    "Zorunlu": "Zorunlu",

    # ---- Words with ğ (soft-g) ----
    "Ag": "Ağ",
    "Agac": "Ağaç",
    "Baglanti": "Bağlantı",
    "Baglantisi": "Bağlantısı",
    "Deger": "Değer",
    "Dogrula": "Doğrula",
    "Dogrulama": "Doğrulama",
    "Dogmasini": "Doğmasını",
    "Imzalar": "İmzalar",
    "Imzalari": "İmzaları",
    "Istege": "İsteğe",

    # ---- Words with ç (c-with-cedilla) ----
    "Aciklama": "Açıklama",
    "Aciklamasi": "Açıklaması",
    "Cevrimici": "Çevrimiçi",
    "Cop": "Çöp",
    "Gecersiz": "Geçersiz",
    "Kucuk": "Küçük",
    "Sadece": "Sadece",
    "Ucuncu": "Üçüncü",

    # ---- Words with ö ----
    "Bolgesi": "Bölgesi",
    "Cozum": "Çözüm",
    "Gonderim": "Gönderim",
    "Gorus": "Görüş",
    "Gorunur": "Görünür",
    "Goster": "Göster",
    "Klasoru": "Klasörü",
    "Onbellegini": "Önbelleğini",
    "Ozel": "Özel",
    "Yonetici": "Yönetici",
    "Yonlendirme": "Yönlendirme",

    # ---- Words with ü ----
    "Cop": "Çöp",
    "Guncelleme": "Güncelleme",
    "Guncellemeleri": "Güncellemeleri",
    "Gunluk": "Günlük",
    "Kucuk": "Küçük",
    "Mumkun": "Mümkün",
    "Surum": "Sürüm",
    "Surumu": "Sürümü",
    "Surumunu": "Sürümünü",
    "Suresi": "Süresi",
    "Turu": "Türü",
    "Ucuncu": "Üçüncü",
    "Yukle": "Yükle",
    "Yuklenecek": "Yüklenecek",
    "Yukleyici": "Yükleyici",
    "Yukleyicisi": "Yükleyicisi",
    "Yuksekligi": "Yüksekliği",

    # ---- Words with İ (capital I with dot) ----
    "Indirme": "İndirme",
    "Insa": "İnşa",
    "Izin": "İzin",
    "Istemci": "İstemci",
    "Istege": "İsteğe",

    # ---- Compound words / common phrases ----
    "Aciklama Metni": "Açıklama Metni",
    "Ag Testini Atla": "Ağ Testini Atla",
    "Agac Yeniden Buyumesi": "Ağaç Yeniden Büyümesi",
    "Ana Dunya Olusumu Gecersiz Kilma": "Ana Dünya Oluşumu Geçersiz Kılma",
    "Atolye Icerigini Kullan": "Atölye İçeriğini Kullan",
    "Baslangic Haritasi": "Başlangıç Haritası",
    "Beyaz Listeyi Etkinlestir": "Beyaz Listeyi Etkinleştir",
    "Canavar Dogmasini Etkinlestir": "Canavar Doğmasını Etkinleştir",
    "Cevrimici Mod": "Çevrimiçi Mod",
    "Chunk Cop Toplama": "Chunk Çöp Toplama",
    "Daha Karanlik Geceler": "Daha Karanlık Geceler",
    "Derleme Numarasi": "Derleme Numarası",
    "Derleme Turu": "Derleme Türü",
    "Devre Disi Birak": "Devre Dışı Bırak",
    "Devre Disi Birakma": "Devre Dışı Bırakma",
    "Dogma Korumasi": "Doğma Koruması",
    "Dunya Adi": "Dünya Adı",
    "Dunya Boyutu": "Dünya Boyutu",
    "Dunya Tohumu": "Dünya Tohumu",
    "Ek Argumanlar": "Ek Argümanlar",
    "Ekstra Baslangic Parametreleri": "Ekstra Başlangıç Parametreleri",
    "Erken Eklentileri Kabul Et": "Erken Eklentileri Kabul Et",
    "Etkinlestir": "Etkinleştir",
    "Etkinlestirme Araligi": "Etkinleştirme Aralığı",
    "Etkinlestirir": "Etkinleştirir",
    "FXServer Surumu": "FXServer Sürümü",
    "Gorus Mesafesi": "Görüş Mesafesi",
    "Guvenli veya Guvensiz": "Güvenli veya Güvensiz",
    "Harita Adi": "Harita Adı",
    "Harita Tipi": "Harita Tipi",
    "Harita Tohumu": "Harita Tohumu",
    "Hayvan Dogmasini Etkinlestir": "Hayvan Doğmasını Etkinleştir",
    "Headless Client (HC)": "Headless Client (HC)",
    "Hilelere Izin Ver": "Hilelere İzin Ver",
    "HTTP Kullan": "HTTP Kullan",
    "Istege Bagli Istemci Tarafi Modlar": "İsteğe Bağlı İstemci Tarafı Modlar",
    "JMX'i Etkinlestir": "JMX'i Etkinleştir",
    "Kalici Savas Alani": "Kalıcı Savaş Alanı",
    "Kaydetme Araligi": "Kaydetme Aralığı",
    "Kaydetmeyi Devre Disi Birak": "Kaydetmeyi Devre Dışı Bırak",
    "Kimlik Dogrulama Anahtari": "Kimlik Doğrulama Anahtarı",
    "Kimlik Dogrulama Modu": "Kimlik Doğrulama Modu",
    "Komut Bloklarini Etkinlestir": "Komut Bloklarını Etkinleştir",
    "Konsolu Etkinlestir": "Konsolu Etkinleştir",
    "Kullanilabilir Moduller": "Kullanılabilir Modüller",
    "Logo Goster": "Logo Göster",
    "Magara Dunya Olusumu Gecersiz Kilma": "Mağara Dünya Oluşumu Geçersiz Kılma",
    "Maksimum Dunya Boyutu": "Maksimum Dünya Boyutu",
    "Maksimum Insa Yuksekligi": "Maksimum İnşa Yüksekliği",
    "Maksimum Istemci Sayisi": "Maksimum İstemci Sayısı",
    "Maksimum Oyuncu Sayisi": "Maksimum Oyuncu Sayısı",
    "Maksimum Arac Sayisi": "Maksimum Araç Sayısı",
    "Maksimum Yapay Zeka": "Maksimum Yapay Zeka",
    "Mod Dosyalarini Kucuk Harf Yap": "Mod Dosyalarını Küçük Harf Yap",
    "Mod Indirme/Guncellemeleri Devre Disi Birak": "Mod İndirme/Güncellemeleri Devre Dışı Bırak",
    "Mod Listesi Dosyasi": "Mod Listesi Dosyası",
    "Mod Paketi Surumu": "Mod Paketi Sürümü",
    "Mod Paketi Surum ID": "Mod Paketi Sürüm ID",
    "Nether'a Izin Ver": "Nether'a İzin Ver",
    "NPC Dogmasini Etkinlestir": "NPC Doğmasını Etkinleştir",
    "Otomatik Baslatma": "Otomatik Başlatma",
    "Otomatik Guncelleme": "Otomatik Güncelleme",
    "Otomatik Guncellemeler": "Otomatik Güncellemeler",
    "Otomatik Katilabilir": "Otomatik Katılabilir",
    "Otomatik Kaydetme Araligi": "Otomatik Kaydetme Aralığı",
    "Otomatik Yeniden Baslatma Modu": "Otomatik Yeniden Başlatma Modu",
    "Oyun Modu": "Oyun Modu",
    "Oyun Modunu Zorla": "Oyun Modunu Zorla",
    "Oyun Sunucusu Kurulumunu Atla": "Oyun Sunucusu Kurulumunu Atla",
    "Oyun Surumu": "Oyun Sürümü",
    "Oyun Surumunu Zorla": "Oyun Sürümünü Zorla",
    "Proje Aciklamasi": "Proje Açıklaması",
    "RCON'u Etkinlestir": "RCON'u Etkinleştir",
    "RCON Sifresi": "RCON Şifresi",
    "Senaryo ID": "Senaryo ID",
    "Sentry'yi Devre Disi Birak": "Sentry'yi Devre Dışı Bırak",
    "Serilestirme Modu": "Serileştirme Modu",
    "Sorguyu Etkinlestir": "Sorguyu Etkinleştir",
    "Source Query Eklentisini Yukle": "Source Query Eklentisini Yükle",
    "Spawn Korumasi": "Spawn Koruması",
    "Steam Dogrulama": "Steam Doğrulama",
    "Steam Dogrulama Kodu": "Steam Doğrulama Kodu",
    "Steam Kullanici Adi": "Steam Kullanıcı Adı",
    "Steam Oyun Giris Anahtari": "Steam Oyun Giriş Anahtarı",
    "Steam Oyun Sunucusu Giris Anahtari": "Steam Oyun Sunucusu Giriş Anahtarı",
    "Sunucu Aciklamasi": "Sunucu Açıklaması",
    "Sunucu Aciklama Metni": "Sunucu Açıklama Metni",
    "Sunucu Ana Bilgisayar Adi": "Sunucu Ana Bilgisayar Adı",
    "Sunucu Binary'si": "Sunucu Binary'si",
    "Sunucu Bolgesi": "Sunucu Bölgesi",
    "Sunucu Dosyalarini Dogrula": "Sunucu Dosyalarını Doğrula",
    "Sunucu Genel Aciklamasi": "Sunucu Genel Açıklaması",
    "Sunucu Genel Adi": "Sunucu Genel Adı",
    "Sunucu Haritasi": "Sunucu Haritası",
    "Sunucu IP Adresi": "Sunucu IP Adresi",
    "Sunucu Jar Dosyasi": "Sunucu Jar Dosyası",
    "Sunucu Modlari": "Sunucu Modları",
    "Sunucu Otomatik Guncelleme": "Sunucu Otomatik Güncelleme",
    "Sunucu Oyun Portu": "Sunucu Oyun Portu",
    "Sunucu Oyuncu Limiti": "Sunucu Oyuncu Limiti",
    "Sunucu Oyuncu Sayisi": "Sunucu Oyuncu Sayısı",
    "Sunucu Sorgu Portu": "Sunucu Sorgu Portu",
    "Sunucu Steam Portu": "Sunucu Steam Portu",
    "Sunucu Tarayicisinda Gorunur": "Sunucu Tarayıcısında Görünür",
    "Ucuncu Sahis Kamerayi Devre Disi Birak": "Üçüncü Şahıs Kamerayı Devre Dışı Bırak",
    "Ucusa Izin Ver": "Uçuşa İzin Ver",
    "UPnP ile Otomatik Port Yonlendirme": "UPnP ile Otomatik Port Yönlendirme",
    "Varsayilan Harita": "Varsayılan Harita",
    "Varsayilan Klasoru Kopyala": "Varsayılan Klasörü Kopyala",
    "VoN'u Devre Disi Birak": "VoN'u Devre Dışı Bırak",
    "Yapi Olusumunu Etkinlestir": "Yapı Oluşumunu Etkinleştir",
    "Yapilandirma": "Yapılandırma",
    "Yapilandirma Dizini": "Yapılandırma Dizini",
    "Yerel Ses Kullan": "Yerel Ses Kullan",
    "Yerel Transport Kullan": "Yerel Transport Kullan",
    "Yuklenecek Surum": "Yüklenecek Sürüm",
    "Yalnizca Gonderim Araligi Kullan": "Yalnızca Gönderim Aralığı Kullan",
    "Yalnizca Sunucu Tarafi Modlar": "Yalnızca Sunucu Tarafı Modlar",
    "Zorunlu Kurulum": "Zorunlu Kurulum",

    # ---- Words with ü ----
    "Gunduz": "Gündüz",
    "Mumkun": "Mümkün",
    "Moduller": "Modüller",
    "Onceden": "Önceden",
    "Surum": "Sürüm",
    "Yukleme": "Yükleme",
    "Yukleyin": "Yükleyin",

    # ---- Specific remaining words ----
    "Aci": "Açı",
    "Acik": "Açık",
    "Aciklamasi": "Açıklaması",
    "Adanmis": "Adanmış",
    "Adresinden": "Adresinden",
    "Alani": "Alanı",
    "Araligi": "Aralığı",
    "Aralik": "Aralık",
    "Argumanlar": "Argümanlar",
    "Atolye": "Atölye",
    "Ayarlari": "Ayarları",
    "Bagli": "Bağlı",
    "Bagimsiz": "Bağımsız",
    "Bayraklar": "Bayraklar",
    "Bicimlendirme": "Biçimlendirme",
    "Birak": "Bırak",
    "Birakma": "Bırakma",
    "Bilgileri": "Bilgileri",
    "Bolgesi": "Bölgesi",
    "Calistir": "Çalıştır",
    "Carpim": "Çarpım",
    "Cikti": "Çıktı",
    "Ciktisi": "Çıktısı",
    "Ciktilisini": "Çıktılısını",
    "Cok": "Çok",
    "Dakika": "Dakika",
    "Destek": "Destek",
    "Devre": "Devre",
    "Dilim": "Dilim",
    "Dogrulama": "Doğrulama",
    "Dogrulamasi": "Doğrulaması",
    "Dogru": "Doğru",
    "Dunya": "Dünya",
    "Durdur": "Durdur",
    "Duzeltme": "Düzeltme",
    "Ekran": "Ekran",
    "Esleme": "Eşleme",
    "Etiket": "Etiket",
    "Etkin": "Etkin",
    "Gece": "Gece",
    "Gecerli": "Geçerli",
    "Gecerlilik": "Geçerlilik",
    "Gelismis": "Gelişmiş",
    "Genel": "Genel",
    "Gerektirir": "Gerektirir",
    "Giris": "Giriş",
    "Gizle": "Gizle",
    "Gizli": "Gizli",
    "Gosterim": "Gösterim",
    "Goruntu": "Görüntü",
    "Guncelle": "Güncelle",
    "Gunluk": "Günlük",
    "Hakkinda": "Hakkında",
    "Harici": "Harici",
    "Hata": "Hata",
    "Hatalari": "Hataları",
    "Hatirlatma": "Hatırlatma",
    "Hesap": "Hesap",
    "Hizli": "Hızlı",
    "Hizmet": "Hizmet",
    "Ic": "İç",
    "Icerigi": "İçeriği",
    "Icin": "İçin",
    "Ilerleme": "İlerleme",
    "Imza": "İmza",
    "Indir": "İndir",
    "Insa": "İnşa",
    "Izin": "İzin",
    "Izleme": "İzleme",
    "Kabul": "Kabul",
    "Kalan": "Kalan",
    "Kapali": "Kapalı",
    "Karanlik": "Karanlık",
    "Kart": "Kart",
    "Kaydet": "Kaydet",
    "Kayit": "Kayıt",
    "Kesin": "Kesin",
    "Kismi": "Kısmı",
    "Kisitlama": "Kısıtlama",
    "Klasor": "Klasör",
    "Koleksiyon": "Koleksiyon",
    "Komut": "Komut",
    "Konum": "Konum",
    "Korumali": "Korumalı",
    "Kullan": "Kullan",
    "Kullanici": "Kullanıcı",
    "Kurallar": "Kurallar",
    "Kursun": "Kurşun",
    "Kurulum": "Kurulum",
    "Kurulumu": "Kurulumu",
    "Listesi": "Listesi",
    "Maksimum": "Maksimum",
    "Modlar": "Modlar",
    "Numara": "Numara",
    "Olustur": "Oluştur",
    "Olusturulan": "Oluşturulan",
    "Onay": "Onay",
    "Onbellek": "Önbellek",
    "Ortak": "Ortak",
    "Otomatik": "Otomatik",
    "Oturum": "Oturum",
    "Oyun": "Oyun",
    "Paylas": "Paylaş",
    "Paylasim": "Paylaşım",
    "Profil": "Profil",
    "Rastgele": "Rastgele",
    "Sahip": "Sahip",
    "Saniye": "Saniye",
    "Savas": "Savaş",
    "Senaryo": "Senaryo",
    "Sifirla": "Sıfırla",
    "Sikistirma": "Sıkıştırma",
    "Sil": "Sil",
    "Sirala": "Sırala",
    "Sohbet": "Sohbet",
    "Sonuc": "Sonuç",
    "Sonuclari": "Sonuçları",
    "Sunucu": "Sunucu",
    "Tamam": "Tamam",
    "Tamamlandi": "Tamamlandı",
    "Tarafindan": "Tarafından",
    "Temel": "Temel",
    "Test": "Test",
    "Toplama": "Toplama",
    "Tum": "Tüm",
    "Ulke": "Ülke",
    "Varsayilan": "Varsayılan",
    "Yabanci": "Yabancı",
    "Yama": "Yama",
    "Yamalama": "Yamalama",
    "Yap": "Yap",
    "Yapay": "Yapay",
    "Yapilandirildi": "Yapılandırıldı",
    "Yavas": "Yavaş",
    "Yenileme": "Yenileme",
    "Yonetim": "Yönetim",
    "Yukle": "Yükle",
    "Yuksek": "Yüksek",
    "Zaman": "Zaman",
    "Zincirleme": "Zincirleme",
    "Zorluk": "Zorluk",
    "Zorunlu": "Zorunlu",

    # ---- Captions/prefixes ----
    "Gelismis": "Gelişmiş",
    "Onarim": "Onarım",
    "Sistem": "Sistem",
    "Baglanti": "Bağlantı",
    "Kullanici": "Kullanıcı",
    "Kullanici Adi": "Kullanıcı Adı",
    "Kullanici Sifresi": "Kullanıcı Şifresi",
}

# ============================================================================
# Fragments to fix in descriptions (English remnants + ASCII Turkish)
# ============================================================================

DESC_FRAGMENT_FIXES = [
    # English fragments → Turkish (original English text that survived translation)
    ("Required to start the service.", "Hizmeti baslatmak icin gereklidir."),
    ("FXServer artifact and replace it with an updated one.", "ve guncellenmis biriyle degistirecektir."),
    ("(default is off)", "(varsayilan: kapali)"),
    ("Read docs for possible values:", "Olası degerler icin dokumantasyona bakin:"),
    ("The description that shows up in the server browser.", "Sunucu tarayicisinda gorunen aciklama."),
    ("Use sending range only.", "Yalnizca gonderim araligini kullanir."),
    ("Specifies the maximum amount of players that are able to join the server.", "Sunucuya katilabilecek maksimum oyuncu sayisini belirler."),
    ("This is to Etkinlestir / Devre Disi Birak auto-updating your server on restart.", "Yeniden baslatmada sunucunun otomatik guncellenmesini etkinlestirir veya devre disi birakir."),
    ("By default this is set to enabled.", "Varsayilan olarak bu etkindir."),
    ("Etkinlestir / Devre Disi Birak VAC (Valve Anti Cheat) on your server. By default this will be enabled.", "Sunucunuzda VAC'i (Valve Anti Cheat) etkinlestirin veya devre disi birakin. Varsayilan olarak bu etkindir."),
    ("Etkinlestir / Devre Disi Birak RCON for using RCON commands with external tools. By default this will be disabled.", "Harici araclarla RCON komutlarini kullanmak icin RCON'u etkinlestirin veya devre disi birakin. Varsayilan olarak bu devre disidir."),
    ("Sets the server name listed in the steam server browser.", "Steam sunucu tarayicisinda listelenen sunucu adini belirler."),
    ("To gain access to administrator commands on the server.", "Sunucudaki yonetici komutlarina erismek icin."),
    ("SourceTV port used for connections to spectates games on your server.", "Sunucunuzdaki oyunlari izlemek icin kullanilan SourceTV portu."),
    ("The token can be acquired here:", "Anahtar su adresten alinabilir:"),
    ("Defines the Gamemode and Gametype to be set at the start of the next round.", "Bir sonraki raundun baslangicinda ayarlanacak Oyun Modu ve Oyun Tipini tanimlar."),
    ("The port for the txAdmin panel.", "txAdmin paneli icin port."),
    ("Enables txAdmin.", "txAdmin'i etkinlestirir."),
    ("The location txAdmin stores data.", "txAdmin'in verileri depoladigi konum."),
    ("Restricts to only running either FiveM or RedM servers.", "Yalnizca FiveM veya RedM sunucularini calistirmakla sinirlar."),
    ("Sets the sv_enforceGameBuild convar. This specifies the client GTA build the server should be on.", "sv_enforceGameBuild convar'ini ayarlar. Sunucunun kullanmasi gereken istemci GTA derlemesini belirtir."),
    ("The setup page will only show recipes for the game specified below!", "Kurulum sayfasi yalnizca asagida belirtilen oyun icin tarifler gosterir!"),
    ("Options are: fivem or redm", "Secenekler: fivem veya redm"),
    ("The username used to authenticate with git.", "Git ile kimlik dogrulamak icin kullanilan kullanici adi."),
    ("The password used to authenticate with git.", "Git ile kimlik dogrulamak icin kullanilan sifre."),
    ("It's best practice to use a Personal Access Token.", "Kisisel Erisim Anahtari kullanmak en iyi uygulamadir."),
    ("URL to Git repository.", "Git deposunun URL'si."),
    ("The name of the branch you wish to use. The default will be used if this is not specified.", "Kullanmak istediginiz dalin adi. Belirtilmezse varsayilan dal kullanilir."),
    ("Sets the maximum player count.", "Maksimum oyuncu sayisini belirler."),
    ("The name that shows up when selecting the server in the server browser.", "Sunucu tarayicisinda sunucu secilirken gorunen ad."),
    ("The name that shows up in the server browser.", "Sunucu tarayicisinda gorunen ad."),
    ("Use your Steam WebApiKey or set to 'none'.", "Steam WebApiKey'inizi kullanin veya 'none' olarak ayarlayin."),
    ("Get your key at", "Anahtarinizi su adresten alin:"),
    ("Get your keys at", "Anahtarlarinizi su adresten alin:"),

    # Partially translated fragments (main script translated some parts, left English)
    ("FXServer artifact.", "FXServer artifact'ini indirir."),
    ("Or specify a direct version to download like", "Veya indirmek icin dogrudan bir surum belirtin, ornegin"),
    ("Pressing 'Reinstall Server' in 'Settings' will remove the currently installed", "'Ayarlar' kismindan 'Sunucuyu Yeniden Kur' tusuna basmak su anda yuklu olani kaldirir"),
    ("Can be set to 'latest', 'recommended', or a specific version.", "'latest', 'recommended' veya belirli bir surum olarak ayarlanabilir."),
    ("You can find the latest version from here -", "En son surumu buradan bulabilirsiniz -"),
    ("The Steam Account Token required for the server to be displayed public.", "Sunucunun herkese acik goruntulenmesi icin gereken Steam Hesap Anahtari."),
    ("Downloads the latest or specified FiveM/RedM FXServer artifact.", "En son veya belirtilen FiveM/RedM FXServer artifact'ini indirir."),
    ("Enable or disable 3d audio. Does nothing if 'UseNativeAudio' is set to true.", "3D sesi etkinlestirir veya devre disi birakir. 'UseNativeAudio' true ise etkisizdir."),
    ("Enable or disable Native audio. You should be using this for the best possible VOIP. Greatly superior to 'Use3dAudio'.", "Yerel sesi etkinlestirir veya devre disi birakir. En iyi VOIP deneyimi icin bunu kullanmalisiniz. 'Use3dAudio'dan cok daha ustundur."),
    ("Set to 'on' to enable Onesync. Set to 'off' if you want to disable Onesync. Optionally you can use 'legacy' however it is strongly advised against. If you are running a server you should have Onesync enabled.", "Onesync'i etkinlestirmek icin 'on', devre disi birakmak icin 'off' yapin. Alternatif olarak 'legacy' kullanilabilir ancak onerilmez. Bir sunucu calistiriyorsaniz Onesync etkin olmalidir."),
    ("Enabling this will clone or pull the specified repository into /resources on each server startup. If you are installing the server now, this will clone the git repo.", "Bunu etkinlestirmek, her sunucu baslangicinda belirtilen depoyu /resources dizinine klonlar veya ceker. Sunucuyu simdi kuruyorsaniz, git deposunu klonlar."),

    # Specific word-level fixes in descriptions
    ("adi.jar dosyasi to run sunucu with.", "Sunucu jar dosyası."),
    ("adi.jarfile to run the server with.", "Sunucu jar dosyası."),
    ("Sunucunun adi.jarfile to run the server with.", "Sunucu jar dosyası."),
    ("FXServer artifact'i kaldiracak ve guncellenmis biriyle degistirecektir.", "ve güncellenmiş biriyle değiştirecektir."),
]


def normalize_turkish(text):
    """Convert ASCII-Turkish text to proper Turkish Unicode."""
    if not text:
        return text

    # Apply word-level replacements (longer phrases first to avoid partial matches)
    # Sort by length descending so longer phrases match first
    sorted_keys = sorted(TR_WORD_MAP.keys(), key=len, reverse=True)
    for key in sorted_keys:
        if key in text:
            text = text.replace(key, TR_WORD_MAP[key])

    # Second pass: case-insensitive common Turkish words not in the main map
    # These are words that commonly appear lowercase in descriptions
    extra_words = {
        "surumu": "sürümü",
        "surumler": "sürümler",
        "surum": "sürüm",
        "surumunu": "sürümünü",
        "guncelleme": "güncelleme",
        "guncellemeler": "güncellemeler",
        "guncellemeleri": "güncellemeleri",
        "guncellemeyi": "güncellemeyi",
        "guncel": "güncel",
        "baglanti": "bağlantı",
        "baglantisi": "bağlantısı",
        "baslangic": "başlangıç",
        "baslangicta": "başlangıçta",
        "baslangicinda": "başlangıcında",
        "baslatma": "başlatma",
        "baslatmak": "başlatmak",
        "baslatir": "başlatır",
        "kullanici": "kullanıcı",
        "kullanicisi": "kullanıcısı",
        "kullanilir": "kullanılır",
        "kullanilan": "kullanılan",
        "kullanin": "kullanın",
        "birakin": "bırakın",
        "birakma": "bırakma",
        "birakmak": "bırakmak",
        "degistirin": "değiştirin",
        "degistirmeyin": "değiştirmeyin",
        "degistirir": "değiştirir",
        "icin": "için",
        "tarafindan": "tarafından",
        "tarafimdan": "tarafımdan",
        "varsayilan": "varsayılan",
        "destegi": "desteği",
        "destekler": "destekler",
        "insa": "inşa",
        "acik": "açık",
        "aciklamasi": "açıklaması",
        "adi": "adı",
        "ornegin": "örneğin",
        "ornek": "örnek",
        "tum": "tüm",
        "gelistirilen": "geliştirilen",
        "gelistirildi": "geliştirildi",
        "gelistirilmis": "geliştirilmiş",
        "tasarlanmis": "tasarlanmış",
        "diger": "diğer",
        "katilmak": "katılmak",
        "katilabilir": "katılabilir",
        "katilabilecek": "katılabilecek",
        "cesitli": "çeşitli",
        "cesit": "çeşit",
        "modlari": "modları",
        "guclu": "güçlü",
        "guvenli": "güvenli",
        "guvensiz": "güvensiz",
        "uzere": "üzere",
        "yapin": "yapın",
        "sifreyi": "şifreyi",
        "sifre": "şifre",
        "arac": "araç",
        "yuklu": "yüklü",
        "yukleme": "yükleme",
        "yukleyin": "yükleyin",
        "yuksek": "yüksek",
        "yuksekligi": "yüksekliği",
        "silahlar": "silahlar",
        "gorunen": "görünen",
        "gorunur": "görünür",
        "goruntulenemez": "görüntülenemez",
        "goruntulemek": "görüntülemek",
        "gosterir": "gösterir",
        "gonderim": "gönderim",
        "cozum": "çözüm",
        "cogunlukla": "çoğunlukla",
        "cogu": "çoğu",
        "cok": "çok",
        "calistiriyorsaniz": "çalıştırıyorsanız",
        "calistirmak": "çalıştırmak",
        "calistirmakla": "çalıştırmakla",
        "calisan": "çalışan",
        "calisir": "çalışır",
        "dogrulama": "doğrulama",
        "dogrulamak": "doğrulamak",
        "dogru": "doğru",
        "dogrudan": "doğrudan",
        "kaldiracaktir": "kaldıracaktır",
        "degistirecektir": "değiştirecektir",
        "degistirerek": "değiştirerek",
        "degisiklik": "değişiklik",
        "degisiklikler": "değişiklikler",
        "otomatik": "otomatik",
        "ozel": "özel",
        "ozellik": "özellik",
        "ozellikle": "özellikle",
        "ozellikler": "özellikler",
        "onemli": "önemli",
        "oncelikle": "öncelikle",
        "onerilmez": "önerilmez",
        "onermek": "önermek",
        "kayit": "kayıt",
        "kaydetme": "kaydetme",
        "sorgu": "sorgu",
        "sorgulama": "sorgulama",
        "sure": "süre",
        "suresi": "süresi",
        "suresini": "süresini",
        "secenek": "seçenek",
        "secenekler": "seçenekler",
        "sayisi": "sayısı",
        "sayisini": "sayısını",
        "sayida": "sayıda",
        "yapilandirma": "yapılandırma",
        "yapilandirilmasi": "yapılandırılması",
        "yapilandir": "yapılandır",
        "yapilandirilmis": "yapılandırılmış",
        "degistirilebilir": "değiştirilebilir",
        "degistirebilir": "değiştirebilir",
        "degistirme": "değiştirme",
        "acmak": "açmak",
        "acilir": "açılır",
        "acma": "açma",
        "ayarlari": "ayarları",
        "ayarlamak": "ayarlamak",
        "ayarlanabilir": "ayarlanabilir",
        "ayar": "ayar",
        "ayarlar": "ayarlar",
        "belirtir": "belirtir",
        "belirtilen": "belirtilen",
        "belirtilmemisse": "belirtilmemişse",
        "belirtilmezse": "belirtilmezse",
        "dogmasini": "doğmasını",
        "dogma": "doğma",
        "korumasi": "koruması",
        "korumak": "korumak",
        "cikti": "çıktı",
        "ciktisi": "çıktısı",
        "ciktilisini": "çıktılısını",
        "giris": "giriş",
        "girisi": "girişi",
        "girilen": "girilen",
        "girin": "girin",
        "etkinlestir": "etkinleştir",
        "etkinlestirme": "etkinleştirme",
        "etkinlestirir": "etkinleştirir",
        "etkinlestirmek": "etkinleştirmek",
        "etkin": "etkin",
        "etkinlik": "etkinlik",
        "oyuncu": "oyuncu",
        "oyuncular": "oyuncular",
        "oyuncularin": "oyuncuların",
        "oyuncuya": "oyuncuya",
        "oyunu": "oyunu",
        "oyunun": "oyunun",
        "oyunudur": "oyunudur",
        "oynanis": "oynanış",
        "oynanisi": "oynanışı",
        "sunucuya": "sunucuya",
        "sunucunun": "sunucunun",
        "sunucunuzda": "sunucunuzda",
        "sunuculari": "sunucuları",
        "sunucularini": "sunucularını",
        "sunucusu": "sunucusu",
        "istegi": "isteği",
        "istediginiz": "istediğiniz",
        "isteginize": "isteğinize",
        "yapmak": "yapmak",
        "yapmasi": "yapması",
        "yapmaya": "yapmaya",
        "saglamak": "sağlamak",
        "saglar": "sağlar",
        "saglandi": "sağlandı",
        "sadece": "sadece",
        "bagli": "bağlı",
        "baglidir": "bağlıdır",
        "alev": "alev",
        "silin": "silin",
        "yukleyecektir": "yükleyecektir",
        "yuklendikten": "yüklendikten",
        "yuklenir": "yüklenir",
        "yuklemek": "yüklemek",
        "yuklemeyi": "yüklemeyi",
        "yuklenebilir": "yüklenebilir",
        "kullanmak": "kullanmak",
        "kullanmasi": "kullanması",
        "kullanmalisiniz": "kullanmalısınız",
        "kullanmaktadir": "kullanmaktadır",
        "bulunur": "bulunur",
        "bulunmaktadir": "bulunmaktadır",
        "bulunmamaktadir": "bulunmamaktadır",
        "yazilmis": "yazılmış",
        "yazilmistir": "yazılmıştır",
        "oldugunca": "olduğunca",
        "oldugu": "olduğu",
        "oldukca": "oldukça",
        "olusturma": "oluşturma",
        "olusturmak": "oluşturmak",
        "olusturur": "oluşturur",
        "olusturulan": "oluşturulan",
        "olusumu": "oluşumu",
        "olusumunu": "oluşumunu",
        "acisindan": "açısından",
        "aciklamak": "açıklamak",
        "eklenti": "eklenti",
        "eklentileri": "eklentileri",
        "eklentiler": "eklentiler",
        "eklentisini": "eklentisini",
        "eklentisi": "eklentisi",
        "yukleyici": "yükleyici",
        "yukleyicisi": "yükleyicisi",
        "yukleyicisidir": "yükleyicisidir",
        "dosya": "dosya",
        "dosyasi": "dosyası",
        "dosyasini": "dosyasını",
        "dosyalari": "dosyaları",
        "dosyalarini": "dosyalarını",
        "klasor": "klasör",
        "klasoru": "klasörü",
        "klonlar": "klonlar",
        "ceker": "çeker",
        "depoyu": "depoyu",
        "deposu": "deposu",
        "deposunu": "deposunu",
        "depolanan": "depolanan",
        "depoladigi": "depoladığı",
        "saglayan": "sağlayan",
        "saglamakta": "sağlamakta",
        "disk": "disk",
        "alani": "alanı",
        "senaryo": "senaryo",
        "senaryolar": "senaryolar",
        "senaryolari": "senaryoları",
        "senaryolarinizi": "senaryolarınızı",
        "senaryosu": "senaryosu",
        "gorev": "görev",
        "gorevleri": "görevleri",
        "gorevler": "görevler",
        "gosterge": "gösterge",
        "panel": "panel",
        "paneli": "paneli",
        "paneline": "paneline",
        "panelinde": "panelinde",
        "panelindeki": "panelindeki",
        "panelini": "panelini",
        "portu": "portu",
        "portundan": "portundan",
        "portuna": "portuna",
        "portudur": "portudur",
        "porttur": "porttur",
        "goruntulemek": "görüntülemek",
        "goruntulenir": "görüntülenir",
        "goruntulenmesi": "görüntülenmesi",
        "goruntulenebilir": "görüntülenebilir",
        "goruntulemeye": "görüntülemeye",
        "goruntulemeyi": "görüntülemeyi",
        # Additional Turkish words in descriptions
        "anahtarlarinizi": "anahtarlarınızı",
        "anahtarinizi": "anahtarınızı",
        "anahtari": "anahtarı",
        "alin": "alın",
        "ayarlayin": "ayarlayın",
        "sirasinda": "sırasında",
        "gore": "göre",
        "kaynaklarini": "kaynaklarını",
        "aciksa": "açıksa",
        "yok": "yok",
        "sayilir": "sayılır",
        "kismindan": "kısmından",
        "tusuna": "tuşuna",
        "basmak": "basmak",
        "olani": "olanı",
        "oldugunca": "olduğunca",
        "oldugu": "olduğu",
        "tutarsizliklarini": "tutarsızlıklarını",
        "duzeltmeyi": "düzeltmeyi",
        "amaclayan": "amaçlayan",
        "catallanmasi": "çatallanması",
        "catallanmasidir": "çatallanmasıdır",
        "performansli": "performanslı",
        "performansi": "performansı",
        "performansini": "performansını",
        "surumudur": "sürümüdür",
        "modlanmis": "modlanmış",
        "odullu": "ödüllü",
        "takim": "takım",
        "aksiyonunu": "aksiyonunu",
        "birlestiriyor": "birleştiriyor",
        "cagir": "çağır",
        "acan": "açan",
        "adanmis": "adanmış",
        "sunucudur": "sunucudur",
        "sunucusudur": "sunucusudur",
        "saglandi": "sağlandı",
        "saglamakta": "sağlamakta",
        "tasarlandi": "tasarlandı",
        "kullanilmak": "kullanılmak",
        "uzerine": "üzerine",
        "donanim": "donanım",
        "donanimi": "donanımı",
        "donanimina": "donanımına",
        "yazilim": "yazılım",
        "yazilimi": "yazılımı",
        "yazilimdir": "yazılımdır",
        "yazilimina": "yazılımına",
        "islemci": "işlemci",
        "isletim": "işletim",
        "sistemi": "sistemi",
        "sistemidir": "sistemidir",
        "sistemine": "sistemine",
        "sisteminde": "sisteminde",
        "sistemini": "sistemini",
    }

    for old, new in extra_words.items():
        # Match whole words only (surrounded by word boundaries or string start/end)
        pattern = re.compile(r'(?<![a-zA-ZğĞüÜşŞıİöÖçÇ])' + re.escape(old) + r'(?![a-zA-ZğĞüÜşŞıİöÖçÇ])')
        text = pattern.sub(new, text)

    return text


def fix_description_fragments(desc):
    """Fix remaining English fragments in descriptions + normalize."""
    if not desc:
        return desc

    for old, new in DESC_FRAGMENT_FIXES:
        if old in desc:
            desc = desc.replace(old, new)

    return desc


def process_file(filepath):
    """Process a single JSON file: normalize Turkish and fix English fragments."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    changed = False

    # Normalize top-level description
    if 'description' in data:
        new_desc = normalize_turkish(data['description'])
        new_desc = fix_description_fragments(new_desc)
        if new_desc != data['description']:
            data['description'] = new_desc
            changed = True

    # Normalize variable names and descriptions
    if 'variables' in data:
        for var in data['variables']:
            if 'name' in var:
                new_name = normalize_turkish(var['name'])
                if new_name != var['name']:
                    var['name'] = new_name
                    changed = True
            if 'description' in var:
                new_desc = normalize_turkish(var['description'])
                new_desc = fix_description_fragments(new_desc)
                if new_desc != var['description']:
                    var['description'] = new_desc
                    changed = True

    if changed:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

    return changed


def main():
    root = 'C:/Users/burak/Desktop/VEHOZER/EGGS/translated_eggs'
    total = 0
    changed = 0

    for dirpath, dirnames, filenames in os.walk(root):
        for fn in sorted(filenames):
            if fn.endswith('.json'):
                total += 1
                filepath = os.path.join(dirpath, fn)
                if process_file(filepath):
                    changed += 1
                    print(f"  Fixed: {os.path.relpath(filepath, root)}")

    print(f"\nTotal files: {total}, Fixed: {changed}")


if __name__ == '__main__':
    main()
