#!/usr/bin/env python3
"""
Turkish ASCII-to-Unicode normalizer for Pterodactyl egg translations.
Karakter seviyesinde ASCII-Türkçe -> düzgün Türkçe Unicode dönüşümü yapar.

Yaklaşım: Türkçe metinlerdeki tüm ASCII-Türkçe kelimeleri kapsamlı bir
sözlükle düzgün Unicode'a çevirir. Kelime tabanlı değil, metin akışı
içinde geçen tüm varyantları (çekimli fiiller, çoğul isimler vb.) kapsar.
"""

import json
import os
import re

# ============================================================================
# KAPSAMLI TÜRKÇE ASCII->UNICODE KELİME HARİTASI
# Kelime bazında birebir eşleme. Uzun bileşik ifadeler önce gelir.
# ============================================================================

TR_WORD_MAP = {}

def _add(*pairs):
    """Her çift (ascii, unicode) için haritaya ekle."""
    for ascii_word, uni_word in pairs:
        if ascii_word != uni_word:
            TR_WORD_MAP[ascii_word] = uni_word

# --- BİLEŞİK DEĞİŞKEN İSİMLERİ (önce bunlar eşleşmeli) ---
_add(
    ("Aciklama Metni", "Açıklama Metni"),
    ("Ag Testini Atla", "Ağ Testini Atla"),
    ("Ag Yeniden Buyumesi", "Ağ Yeniden Büyümesi"),
    ("Agac Yeniden Buyumesi", "Ağaç Yeniden Büyümesi"),
    ("Ana Dunya Olusumu Gecersiz Kilma", "Ana Dünya Oluşumu Geçersiz Kılma"),
    ("Atolye Icerigini Kullan", "Atölye İçeriğini Kullan"),
    ("Atolye Koleksiyon ID", "Atölye Koleksiyon ID"),
    ("Baslangic Haritasi", "Başlangıç Haritası"),
    ("Bedrock Adanmis Sunucu Surumu", "Bedrock Adanmış Sunucu Sürümü"),
    ("Beyaz Listeyi Etkinlestir", "Beyaz Listeyi Etkinleştir"),
    ("Canavar Dogmasini Etkinlestir", "Canavar Doğmasını Etkinleştir"),
    ("Cevrimici Mod", "Çevrimiçi Mod"),
    ("Chunk Cop Toplama", "Chunk Çöp Toplama"),
    ("Daha Karanlik Geceler", "Daha Karanlık Geceler"),
    ("Derleme Numarasi", "Derleme Numarası"),
    ("Derleme Turu", "Derleme Türü"),
    ("Devre Disi Birak", "Devre Dışı Bırak"),
    ("Devre Disi Birakma", "Devre Dışı Bırakma"),
    ("Dogma Korumasi", "Doğma Koruması"),
    ("Dunya Adi", "Dünya Adı"),
    ("Dunya Boyutu", "Dünya Boyutu"),
    ("Dunya Tohumu", "Dünya Tohumu"),
    ("Ek Argumanlar", "Ek Argümanlar"),
    ("Ekstra Baslangic Parametreleri", "Ekstra Başlangıç Parametreleri"),
    ("Erken Eklentileri Kabul Et", "Erken Eklentileri Kabul Et"),
    ("Etkinlestir / Devre Disi Birak", "Etkinleştir / Devre Dışı Bırak"),
    ("Etkinlestirme Araligi", "Etkinleştirme Aralığı"),
    ("FXServer Surumu", "FXServer Sürümü"),
    ("Gorus Mesafesi", "Görüş Mesafesi"),
    ("Guvenli veya Guvensiz", "Güvenli veya Güvensiz"),
    ("Harita Adi", "Harita Adı"),
    ("Harita Tipi", "Harita Tipi"),
    ("Harita Tohumu", "Harita Tohumu"),
    ("Hayvan Dogmasini Etkinlestir", "Hayvan Doğmasını Etkinleştir"),
    ("Headless Client (HC)", "Headless Client (HC)"),
    ("Hilelere Izin Ver", "Hilelere İzin Ver"),
    ("HTTP Kullan", "HTTP Kullan"),
    ("Istege Bagli Istemci Tarafi Modlar", "İsteğe Bağlı İstemci Tarafı Modlar"),
    ("JMX'i Etkinlestir", "JMX'i Etkinleştir"),
    ("Kalici Savas Alani", "Kalıcı Savaş Alanı"),
    ("Kaydetme Araligi", "Kaydetme Aralığı"),
    ("Kaydetmeyi Devre Disi Birak", "Kaydetmeyi Devre Dışı Bırak"),
    ("Kimlik Dogrulama Anahtari", "Kimlik Doğrulama Anahtarı"),
    ("Kimlik Dogrulama Modu", "Kimlik Doğrulama Modu"),
    ("Komut Bloklarini Etkinlestir", "Komut Bloklarını Etkinleştir"),
    ("Konsolu Etkinlestir", "Konsolu Etkinleştir"),
    ("Kullanilabilir Moduller", "Kullanılabilir Modüller"),
    ("Logo Goster", "Logo Göster"),
    ("Magara Dunya Olusumu Gecersiz Kilma", "Mağara Dünya Oluşumu Geçersiz Kılma"),
    ("Maksimum Dunya Boyutu", "Maksimum Dünya Boyutu"),
    ("Maksimum Insa Yuksekligi", "Maksimum İnşa Yüksekliği"),
    ("Maksimum Istemci Sayisi", "Maksimum İstemci Sayısı"),
    ("Maksimum Oyuncu Sayisi", "Maksimum Oyuncu Sayısı"),
    ("Maksimum Arac Sayisi", "Maksimum Araç Sayısı"),
    ("Maksimum Yapay Zeka", "Maksimum Yapay Zeka"),
    ("Mod Dosyalarini Kucuk Harf Yap", "Mod Dosyalarını Küçük Harf Yap"),
    ("Mod Indirme/Guncellemeleri Devre Disi Birak", "Mod İndirme/Güncellemeleri Devre Dışı Bırak"),
    ("Mod Listesi Dosyasi", "Mod Listesi Dosyası"),
    ("Mod Paketi Surumu", "Mod Paketi Sürümü"),
    ("Mod Paketi Surum ID", "Mod Paketi Sürüm ID"),
    ("Nether'a Izin Ver", "Nether'a İzin Ver"),
    ("NPC Dogmasini Etkinlestir", "NPC Doğmasını Etkinleştir"),
    ("Otomatik Baslatma", "Otomatik Başlatma"),
    ("Otomatik Guncelleme", "Otomatik Güncelleme"),
    ("Otomatik Guncellemeler", "Otomatik Güncellemeler"),
    ("Otomatik Katilabilir", "Otomatik Katılabilir"),
    ("Otomatik Kaydetme Araligi", "Otomatik Kaydetme Aralığı"),
    ("Otomatik Yeniden Baslatma Modu", "Otomatik Yeniden Başlatma Modu"),
    ("Oyun Modu", "Oyun Modu"),
    ("Oyun Modunu Zorla", "Oyun Modunu Zorla"),
    ("Oyun Sunucusu Kurulumunu Atla", "Oyun Sunucusu Kurulumunu Atla"),
    ("Oyun Surumu", "Oyun Sürümü"),
    ("Oyun Surumunu Zorla", "Oyun Sürümünü Zorla"),
    ("Proje Aciklamasi", "Proje Açıklaması"),
    ("RCON Sifresi", "RCON Şifresi"),
    ("RCON'u Etkinlestir", "RCON'u Etkinleştir"),
    ("RCON'u Etkinlestir (MC)", "RCON'u Etkinleştir (MC)"),
    ("Senaryo ID", "Senaryo ID"),
    ("Sentry'yi Devre Disi Birak", "Sentry'yi Devre Dışı Bırak"),
    ("Serilestirme Modu", "Serileştirme Modu"),
    ("Sorguyu Etkinlestir", "Sorguyu Etkinleştir"),
    ("Source Query Eklentisini Yukle", "Source Query Eklentisini Yükle"),
    ("Spawn Korumasi", "Spawn Koruması"),
    ("Steam Dogrulama", "Steam Doğrulama"),
    ("Steam Dogrulama Kodu", "Steam Doğrulama Kodu"),
    ("Steam Kullanici Adi", "Steam Kullanıcı Adı"),
    ("Steam Oyun Giris Anahtari", "Steam Oyun Giriş Anahtarı"),
    ("Steam Oyun Sunucusu Giris Anahtari", "Steam Oyun Sunucusu Giriş Anahtarı"),
    ("Sunucu Aciklamasi", "Sunucu Açıklaması"),
    ("Sunucu Aciklama Metni", "Sunucu Açıklama Metni"),
    ("Sunucu Ana Bilgisayar Adi", "Sunucu Ana Bilgisayar Adı"),
    ("Sunucu Binary'si", "Sunucu Binary'si"),
    ("Sunucu Bolgesi", "Sunucu Bölgesi"),
    ("Sunucu Dosyalarini Dogrula", "Sunucu Dosyalarını Doğrula"),
    ("Sunucu Genel Aciklamasi", "Sunucu Genel Açıklaması"),
    ("Sunucu Genel Adi", "Sunucu Genel Adı"),
    ("Sunucu Haritasi", "Sunucu Haritası"),
    ("Sunucu IP Adresi", "Sunucu IP Adresi"),
    ("Sunucu Jar Dosyasi", "Sunucu Jar Dosyası"),
    ("Sunucu Modlari", "Sunucu Modları"),
    ("Sunucu Otomatik Guncelleme", "Sunucu Otomatik Güncelleme"),
    ("Sunucu Oyun Portu", "Sunucu Oyun Portu"),
    ("Sunucu Oyuncu Limiti", "Sunucu Oyuncu Limiti"),
    ("Sunucu Oyuncu Sayisi", "Sunucu Oyuncu Sayısı"),
    ("Sunucu Sorgu Portu", "Sunucu Sorgu Portu"),
    ("Sunucu Steam Portu", "Sunucu Steam Portu"),
    ("Sunucu Tarayicisinda Gorunur", "Sunucu Tarayıcısında Görünür"),
    ("Ucuncu Sahis Kamerayi Devre Disi Birak", "Üçüncü Şahıs Kamerayı Devre Dışı Bırak"),
    ("Ucusa Izin Ver", "Uçuşa İzin Ver"),
    ("UPnP ile Otomatik Port Yonlendirme", "UPnP ile Otomatik Port Yönlendirme"),
    ("Varsayilan Harita", "Varsayılan Harita"),
    ("Varsayilan Klasoru Kopyala", "Varsayılan Klasörü Kopyala"),
    ("VoN'u Devre Disi Birak", "VoN'u Devre Dışı Bırak"),
    ("Yapi Olusumunu Etkinlestir", "Yapı Oluşumunu Etkinleştir"),
    ("Yapilandirma Dizini", "Yapılandırma Dizini"),
    ("Yerel Ses Kullan", "Yerel Ses Kullan"),
    ("Yerel Transport Kullan", "Yerel Transport Kullan"),
    ("Yuklenecek Surum", "Yüklenecek Sürüm"),
    ("Yalnizca Gonderim Araligi Kullan", "Yalnızca Gönderim Aralığı Kullan"),
    ("Yalnizca Sunucu Tarafi Modlar", "Yalnızca Sunucu Tarafı Modlar"),
    ("Zorunlu Kurulum", "Zorunlu Kurulum"),
    ("3D Ses Kullan", "3D Ses Kullan"),
    ("Otomatik Yapilandir", "Otomatik Yapılandır"),
    ("Sunucu Dili", "Sunucu Dili"),
    ("Sunucu Hafizasi", "Sunucu Hafızası"),
    ("Sunucu Surumu", "Sunucu Sürümü"),
    ("Varsayilan Değer", "Varsayılan Değer"),
    ("Yonetici Sifresi", "Yönetici Şifresi"),
    ("Yonetici Kullanici Adi", "Yönetici Kullanıcı Adı"),
    ("Oyun ID", "Oyun ID"),
    ("Oyun Adi", "Oyun Adı"),
    ("Oyun Portu", "Oyun Portu"),
    ("Oyun Tipi", "Oyun Tipi"),
    ("Sifre", "Şifre"),
    ("Sunucu Adi", "Sunucu Adı"),
    ("Sunucu Portu", "Sunucu Portu"),
    ("Sunucu Sifresi", "Sunucu Şifresi"),
    ("Sorgu Portu", "Sorgu Portu"),
    ("Steam Sorgu Portu", "Steam Sorgu Portu"),
    ("Otomatik Guncelleme", "Otomatik Güncelleme"),
    ("Indirme Yolu", "İndirme Yolu"),
    ("Indirme Surumu", "İndirme Sürümü"),
    ("Indirme Baglantisi", "İndirme Bağlantısı"),
    ("Indirme URL", "İndirme URL"),
    ("Kaynak AppID", "Kaynak AppID"),
    ("Uygulama ID", "Uygulama ID"),
    ("Minecraft Surumu", "Minecraft Sürümü"),
    ("Java Surumu", "Java Sürümü"),
    ("Steam Kullanici Sifresi", "Steam Kullanıcı Şifresi"),
    ("Steam Hesap Anahtari", "Steam Hesap Anahtarı"),
    ("Steam Grup ID", "Steam Grup ID"),
    ("SourceTV Portu", "SourceTV Portu"),
    ("HTTP Portu", "HTTP Portu"),
    ("UDP Portu", "UDP Portu"),
    ("TCP Portu", "TCP Portu"),
    ("Web Sunucu Portu", "Web Sunucu Portu"),
    ("WebAdmin Portu", "WebAdmin Portu"),
    ("Sunucu IP'si", "Sunucu IP'si"),
    ("Proje Adi", "Proje Adı"),
    ("Proje ID", "Proje ID"),
    ("Kayit Adi", "Kayıt Adı"),
    ("Kayit Yuvasi", "Kayıt Yuvası"),
    ("Kayit Dosya Yolu", "Kayıt Dosya Yolu"),
    ("Oturum Adi", "Oturum Adı"),
    ("Kume Adi", "Küme Adı"),
    ("Kume Aciklamasi", "Küme Açıklaması"),
    ("Baglanti Platformu", "Bağlantı Platformu"),
    ("Baglanti Portu", "Bağlantı Portu"),
    ("Mod Paketi Proje ID", "Mod Paketi Proje ID"),
    ("Mod Paketi Dosya ID", "Mod Paketi Dosya ID"),
    ("CurseForge API Anahtari", "CurseForge API Anahtarı"),
    ("CFX Lisans Anahtari", "CFX Lisans Anahtarı"),
    ("Steam Web Api Anahtari", "Steam Web Api Anahtarı"),
    ("MySQL Baglanti Dizesi", "MySQL Bağlantı Dizesi"),
    ("Git Kullanici Adi", "Git Kullanıcı Adı"),
    ("Git Anahtari", "Git Anahtarı"),
    ("Git Depo URL'si", "Git Depo URL'si"),
    ("Git Dal", "Git Dal"),
    ("GitHub Dali", "GitHub Dalı"),
    ("GitHub Kullanici Adi", "GitHub Kullanıcı Adı"),
    ("GitHub OAuth Anahtari", "GitHub OAuth Anahtarı"),
    ("GitHub Paketi", "GitHub Paketi"),
    ("Alan Adi", "Alan Adı"),
)

# --- BÜYÜK HARF TEKİL KELİMELER ---
_add(
    # -ı/-i/-u/-ü eki alan isimler
    ("Adi", "Adı"),
    ("Anahtari", "Anahtarı"),
    ("Araligi", "Aralığı"),
    ("Baglantisi", "Bağlantısı"),
    ("Bolgesi", "Bölgesi"),
    ("Boyutu", "Boyutu"),
    ("Carpani", "Çarpanı"),
    ("Ciktisini", "Çıktısını"),
    ("Dali", "Dalı"),
    ("Derlemesi", "Derlemesi"),
    ("Dili", "Dili"),
    ("Dizesi", "Dizesi"),
    ("Dosyasi", "Dosyası"),
    ("Dosyalarini", "Dosyalarını"),
    ("Esigi", "Eşiği"),
    ("Hafizasi", "Hafızası"),
    ("Haritasi", "Haritası"),
    ("Hatti", "Hattı"),
    ("Icerigini", "İçeriğini"),
    ("Isigi", "Işığı"),
    ("Kalitesi", "Kalitesi"),
    ("Kanali", "Kanalı"),
    ("Kimligi", "Kimliği"),
    ("Klasoru", "Klasörü"),
    ("Koleksiyonu", "Koleksiyonu"),
    ("Korumasi", "Koruması"),
    ("Kurallari", "Kuralları"),
    ("Limiti", "Limiti"),
    ("Listesi", "Listesi"),
    ("Mesafesi", "Mesafesi"),
    ("Metni", "Metni"),
    ("Modlari", "Modları"),
    ("Modu", "Modu"),
    ("Numarasi", "Numarası"),
    ("Olusumu", "Oluşumu"),
    ("Onbellegini", "Önbelleğini"),
    ("Paketi", "Paketi"),
    ("Parametreleri", "Parametreleri"),
    ("Platformu", "Platformu"),
    ("Portu", "Portu"),
    ("Sifresi", "Şifresi"),
    ("Suresi", "Süresi"),
    ("Surumu", "Sürümü"),
    ("Surumunu", "Sürümünü"),
    ("Tarafi", "Tarafı"),
    ("Tipi", "Tipi"),
    ("Tohumu", "Tohumu"),
    ("Turu", "Türü"),
    ("Yapilandirmasi", "Yapılandırması"),
    ("Yolu", "Yolu"),
    ("Yukleyici", "Yükleyici"),
    ("Yukleyicisi", "Yükleyicisi"),
    ("Yuksekligi", "Yüksekliği"),
    ("Yuvasi", "Yuvası"),
    ("ID'si", "ID'si"),
    ("IP'si", "IP'si"),
    ("API'si", "API'si"),
    ("URL'si", "URL'si"),

    # ş-li kelimeler (büyük harf)
    ("Baslangic", "Başlangıç"),
    ("Baslangicta", "Başlangıçta"),
    ("Baslatma", "Başlatma"),
    ("Dogmasini", "Doğmasını"),
    ("Eslesme", "Eşleşme"),
    ("Etkinlestir", "Etkinleştir"),
    ("Etkinlestirme", "Etkinleştirme"),
    ("Etkinlestirir", "Etkinleştirir"),
    ("Etkinlestirmek", "Etkinleştirmek"),
    ("Gecersiz", "Geçersiz"),
    ("Giris", "Giriş"),
    ("Goster", "Göster"),
    ("Gorunur", "Görünür"),
    ("Gorus", "Görüş"),
    ("Guvenli", "Güvenli"),
    ("Guvensiz", "Güvensiz"),
    ("Hilelere", "Hilelere"),
    ("Insa", "İnşa"),
    ("Istemci", "İstemci"),
    ("Kisi", "Kişi"),
    ("Kisisel", "Kişisel"),
    ("Kullanilabilir", "Kullanılabilir"),
    ("Kullanicisi", "Kullanıcısı"),
    ("Nisangahi", "Nişangahı"),
    ("Olusturma", "Oluşturma"),
    ("Sifre", "Şifre"),
    ("Sikistirma", "Sıkıştırma"),
    ("Ucusa", "Uçuşa"),
    ("Varlik", "Varlık"),
    ("Yapilandir", "Yapılandır"),
    ("Yapilandirma", "Yapılandırma"),
    ("Yeniden", "Yeniden"),
    ("Yonetici", "Yönetici"),
    ("Yonlendirme", "Yönlendirme"),
    ("Zorunlu", "Zorunlu"),

    # ğ-li kelimeler
    ("Ag", "Ağ"),
    ("Agac", "Ağaç"),
    ("Baglanti", "Bağlantı"),
    ("Bagimsiz", "Bağımsız"),
    ("Deger", "Değer"),
    ("Dogrula", "Doğrula"),
    ("Dogrulama", "Doğrulama"),
    ("Imzalar", "İmzalar"),
    ("Imzalari", "İmzaları"),
    ("Istege", "İsteğe"),

    # ç-li kelimeler
    ("Aciklama", "Açıklama"),
    ("Aciklamasi", "Açıklaması"),
    ("Cevrimici", "Çevrimiçi"),
    ("Cop", "Çöp"),
    ("Kucuk", "Küçük"),
    ("Ucuncu", "Üçüncü"),

    # ö-lü kelimeler
    ("Cozum", "Çözüm"),
    ("Gonderim", "Gönderim"),
    ("Klasoru", "Klasörü"),
    ("Ozel", "Özel"),

    # ü-lü kelimeler
    ("Guncelleme", "Güncelleme"),
    ("Guncellemeleri", "Güncellemeleri"),
    ("Gunluk", "Günlük"),
    ("Mumkun", "Mümkün"),
    ("Surum", "Sürüm"),
    ("Yukle", "Yükle"),
    ("Yuklenecek", "Yüklenecek"),
    ("Yuksekligi", "Yüksekliği"),

    # İ-li kelimeler
    ("Indirme", "İndirme"),
    ("Izin", "İzin"),
    ("Istemci", "İstemci"),
    ("Istege", "İsteğe"),

    # Diğer sık kullanılanlar
    ("Adanmis", "Adanmış"),
    ("Alani", "Alanı"),
    ("Aralik", "Aralık"),
    ("Argumanlar", "Argümanlar"),
    ("Atolye", "Atölye"),
    ("Ayarlari", "Ayarları"),
    ("Bagli", "Bağlı"),
    ("Bayraklar", "Bayraklar"),
    ("Bicimlendirme", "Biçimlendirme"),
    ("Birak", "Bırak"),
    ("Birakma", "Bırakma"),
    ("Bilgileri", "Bilgileri"),
    ("Calistir", "Çalıştır"),
    ("Carpim", "Çarpım"),
    ("Cikti", "Çıktı"),
    ("Cok", "Çok"),
    ("Dilim", "Dilim"),
    ("Dogrulamasi", "Doğrulaması"),
    ("Dogru", "Doğru"),
    ("Dunya", "Dünya"),
    ("Duzeltme", "Düzeltme"),
    ("Esleme", "Eşleme"),
    ("Etkin", "Etkin"),
    ("Gece", "Gece"),
    ("Gecerli", "Geçerli"),
    ("Gecerlilik", "Geçerlilik"),
    ("Gelismis", "Gelişmiş"),
    ("Genel", "Genel"),
    ("Gizle", "Gizle"),
    ("Gizli", "Gizli"),
    ("Gosterim", "Gösterim"),
    ("Goruntu", "Görüntü"),
    ("Guncelle", "Güncelle"),
    ("Hakkinda", "Hakkında"),
    ("Hatalari", "Hataları"),
    ("Hatirlatma", "Hatırlatma"),
    ("Hesap", "Hesap"),
    ("Hizli", "Hızlı"),
    ("Ic", "İç"),
    ("Icin", "İçin"),
    ("Imza", "İmza"),
    ("Indir", "İndir"),
    ("Izleme", "İzleme"),
    ("Kabul", "Kabul"),
    ("Kalici", "Kalıcı"),
    ("Kapali", "Kapalı"),
    ("Karanlik", "Karanlık"),
    ("Kaydet", "Kaydet"),
    ("Kayit", "Kayıt"),
    ("Kismi", "Kısmı"),
    ("Kisitlama", "Kısıtlama"),
    ("Klasor", "Klasör"),
    ("Koleksiyon", "Koleksiyon"),
    ("Konum", "Konum"),
    ("Korumali", "Korumalı"),
    ("Kullanici", "Kullanıcı"),
    ("Kurulum", "Kurulum"),
    ("Kurulumu", "Kurulumu"),
    ("Maksimum", "Maksimum"),
    ("Moduller", "Modüller"),
    ("Numara", "Numara"),
    ("Onarim", "Onarım"),
    ("Onbellek", "Önbellek"),
    ("Onceden", "Önceden"),
    ("Ortak", "Ortak"),
    ("Otomatik", "Otomatik"),
    ("Oturum", "Oturum"),
    ("Paylas", "Paylaş"),
    ("Paylasim", "Paylaşım"),
    ("Profil", "Profil"),
    ("Sahip", "Sahip"),
    ("Savas", "Savaş"),
    ("Senaryo", "Senaryo"),
    ("Sifirla", "Sıfırla"),
    ("Sohbet", "Sohbet"),
    ("Sonuc", "Sonuç"),
    ("Sonuclari", "Sonuçları"),
    ("Sunucu", "Sunucu"),
    ("Sistem", "Sistem"),
    ("Tamam", "Tamam"),
    ("Tamamlandi", "Tamamlandı"),
    ("Tarafindan", "Tarafından"),
    ("Temel", "Temel"),
    ("Toplama", "Toplama"),
    ("Tum", "Tüm"),
    ("Ulke", "Ülke"),
    ("Varsayilan", "Varsayılan"),
    ("Yabanci", "Yabancı"),
    ("Yama", "Yama"),
    ("Yamalama", "Yamalama"),
    ("Yapay", "Yapay"),
    ("Yapilandirildi", "Yapılandırıldı"),
    ("Yavas", "Yavaş"),
    ("Yenileme", "Yenileme"),
    ("Yonetim", "Yönetim"),
    ("Yuksek", "Yüksek"),
    ("Zaman", "Zaman"),
    ("Zincirleme", "Zincirleme"),
    ("Zorluk", "Zorluk"),
    ("Zorunlu", "Zorunlu"),
)

# ============================================================================
# KÜÇÜK HARF KELİME HARİTASI (açıklama metinleri için)
# ============================================================================

LOWER_MAP = {}

def _addl(*pairs):
    for ascii_word, uni_word in pairs:
        if ascii_word != uni_word:
            LOWER_MAP[ascii_word] = uni_word

_addl(
    # --- ÇEKİMLİ FİİLLER / SIFATLAR (doğrulama raporundan gelenler) ---
    ("yaratiklarla", "yaratıklarla"),
    ("savasin", "savaşın"),
    ("ciftcilik", "çiftçilik"),
    ("calisin", "çalışın"),
    ("uretim", "üretim"),
    ("gunceller", "günceller"),
    ("ingiliz", "İngiliz"),
    ("kanadali", "Kanadalı"),
    ("bagimsiz", "bağımsız"),
    ("gelistirici", "geliştirici"),
    ("asamasinda", "aşamasında"),
    ("kacinilmaz", "kaçınılmaz"),
    ("olumden", "ölümden"),
    ("calistigi", "çalıştığı"),
    ("istilasina", "istilasına"),
    ("ugramis", "uğramış"),
    ("gecer", "geçer"),
    ("edilmis", "edilmiş"),
    ("atilin", "atılın"),
    ("ozgurlugunu", "özgürlüğünü"),
    ("sirlar", "sırlar"),
    ("prosedurel", "prosedürel"),
    ("uretilmis", "üretilmiş"),
    ("dunyayi", "dünyayı"),
    ("kesfedin", "keşfedin"),
    ("sekillendirin", "şekillendirin"),
    ("kesfet", "keşfet"),
    ("hicbir", "hiçbir"),
    ("sey", "şey"),
    ("imkansiz", "imkansız"),
    ("degildir", "değildir"),
    ("zirhlar", "zırhlar"),
    ("esyalar", "eşyalar"),
    ("yasam", "yaşam"),
    ("formlarinin", "formlarının"),
    ("yasadigi", "yaşadığı"),
    ("kesfedebilecegi", "keşfedebileceği"),
    ("olusturulmus", "oluşturulmuş"),
    # Eksik kalan kritik kelimeler
    ("dunya", "dünya"),
    ("dunyada", "dünyada"),
    ("dunyadaki", "dünyadaki"),
    ("dunyanin", "dünyanın"),
    ("dunyayi", "dünyayı"),
    ("dunyasi", "dünyası"),
    ("dunyasinda", "dünyasında"),
    ("dunyasini", "dünyasını"),
    ("dunyasina", "dünyasına"),
    ("once", "önce"),
    ("savas", "savaş"),
    ("mumkun", "mümkün"),
    ("oyununda", "oyununda"),
    ("oyuncunun", "oyuncunun"),
    ("gecer", "geçer"),
    ("macera", "macera"),
    ("maceralara", "maceralara"),
    ("aksiyon", "aksiyon"),
    ("korku", "korku"),


    # --- GENEL İSİM ÇEKİMLERİ ---
    ("surumu", "sürümü"),
    ("surum", "sürüm"),
    ("surumler", "sürümler"),
    ("surumunu", "sürümünü"),
    ("surumudur", "sürümüdür"),
    ("surumleri", "sürümleri"),
    ("guncelleme", "güncelleme"),
    ("guncellemeler", "güncellemeler"),
    ("guncellemeleri", "güncellemeleri"),
    ("guncellemeyi", "güncellemeyi"),
    ("guncellenmis", "güncellenmiş"),
    ("guncel", "güncel"),
    ("baglanti", "bağlantı"),
    ("baglantisi", "bağlantısı"),
    ("baglantisini", "bağlantısını"),
    ("baslangic", "başlangıç"),
    ("baslangicta", "başlangıçta"),
    ("baslangicinda", "başlangıcında"),
    ("baslatma", "başlatma"),
    ("baslatmak", "başlatmak"),
    ("baslatir", "başlatır"),
    ("baslatildi", "başlatıldı"),
    ("kullanici", "kullanıcı"),
    ("kullanicisi", "kullanıcısı"),
    ("kullanilir", "kullanılır"),
    ("kullanilan", "kullanılan"),
    ("kullanin", "kullanın"),
    ("kullanmak", "kullanmak"),
    ("kullanmasi", "kullanması"),
    ("kullanmalisiniz", "kullanmalısınız"),
    ("kullanmaktadir", "kullanmaktadır"),
    ("kullanildigi", "kullanıldığı"),
    ("birakin", "bırakın"),
    ("birakma", "bırakma"),
    ("birakmak", "bırakmak"),
    ("birakilir", "bırakılır"),
    ("degistirin", "değiştirin"),
    ("degistirmeyin", "değiştirmeyin"),
    ("degistirir", "değiştirir"),
    ("degistirerek", "değiştirerek"),
    ("degisiklik", "değişiklik"),
    ("degisiklikler", "değişiklikler"),
    ("degistirecektir", "değiştirecektir"),
    ("degistirilebilir", "değiştirilebilir"),
    ("degistirebilir", "değiştirebilir"),
    ("degistirme", "değiştirme"),
    ("icin", "için"),
    ("tarafindan", "tarafından"),
    ("varsayilan", "varsayılan"),
    ("destegi", "desteği"),
    ("destekler", "destekler"),
    ("insa", "inşa"),
    ("acik", "açık"),
    ("aciklamasi", "açıklaması"),
    ("adi", "adı"),
    ("adresinden", "adresinden"),
    ("ornegin", "örneğin"),
    ("ornek", "örnek"),
    ("ornekler", "örnekler"),
    ("tum", "tüm"),
    ("gelistirilen", "geliştirilen"),
    ("gelistirildi", "geliştirildi"),
    ("gelistirilmis", "geliştirilmiş"),
    ("tasarlanmis", "tasarlanmış"),
    ("diger", "diğer"),
    ("katilmak", "katılmak"),
    ("katilabilir", "katılabilir"),
    ("katilabilecek", "katılabilecek"),
    ("cesitli", "çeşitli"),
    ("cesit", "çeşit"),
    ("modlari", "modları"),
    ("guclu", "güçlü"),
    ("guvenli", "güvenli"),
    ("guvensiz", "güvensiz"),
    ("uzere", "üzere"),
    ("yapin", "yapın"),
    ("sifreyi", "şifreyi"),
    ("arac", "araç"),
    ("yuklu", "yüklü"),
    ("yukleme", "yükleme"),
    ("yukleyin", "yükleyin"),
    ("yuksek", "yüksek"),
    ("yuksekligi", "yüksekliği"),
    ("gorunen", "görünen"),
    ("gorunur", "görünür"),
    ("goruntulenemez", "görüntülenemez"),
    ("goruntulemek", "görüntülemek"),
    ("gosterir", "gösterir"),
    ("gonderim", "gönderim"),
    ("cozum", "çözüm"),
    ("cogunlukla", "çoğunlukla"),
    ("cogu", "çoğu"),
    ("cok", "çok"),
    ("calistiriyorsaniz", "çalıştırıyorsanız"),
    ("calistirmak", "çalıştırmak"),
    ("calistirmakla", "çalıştırmakla"),
    ("calisan", "çalışan"),
    ("calisir", "çalışır"),
    ("dogrulama", "doğrulama"),
    ("dogrulamak", "doğrulamak"),
    ("dogru", "doğru"),
    ("dogrudan", "doğrudan"),
    ("kaldiracaktir", "kaldıracaktır"),
    ("kaldiracak", "kaldıracak"),
    ("degistirecektir", "değiştirecektir"),
    ("otomatik", "otomatik"),
    ("ozel", "özel"),
    ("ozellik", "özellik"),
    ("ozellikle", "özellikle"),
    ("ozellikler", "özellikler"),
    ("onemli", "önemli"),
    ("oncelikle", "öncelikle"),
    ("onerilmez", "önerilmez"),
    ("onermek", "önermek"),
    ("kayit", "kayıt"),
    ("kaydetme", "kaydetme"),
    ("sorgu", "sorgu"),
    ("sorgulama", "sorgulama"),
    ("sure", "süre"),
    ("suresi", "süresi"),
    ("suresini", "süresini"),
    ("secenek", "seçenek"),
    ("secenekler", "seçenekler"),
    ("sayisi", "sayısı"),
    ("sayisini", "sayısını"),
    ("sayida", "sayıda"),
    ("yapilandirma", "yapılandırma"),
    ("yapilandirilmasi", "yapılandırılması"),
    ("yapilandir", "yapılandır"),
    ("yapilandirilmis", "yapılandırılmış"),
    ("acmak", "açmak"),
    ("acilir", "açılır"),
    ("acma", "açma"),
    ("ayarlari", "ayarları"),
    ("ayarlamak", "ayarlamak"),
    ("ayarlanabilir", "ayarlanabilir"),
    ("ayar", "ayar"),
    ("ayarlar", "ayarlar"),
    ("belirtir", "belirtir"),
    ("belirtilen", "belirtilen"),
    ("belirtilmemisse", "belirtilmemişse"),
    ("belirtilmezse", "belirtilmezse"),
    ("dogmasini", "doğmasını"),
    ("dogma", "doğma"),
    ("korumasi", "koruması"),
    ("korumak", "korumak"),
    ("cikti", "çıktı"),
    ("ciktisi", "çıktısı"),
    ("ciktilisini", "çıktılısını"),
    ("giris", "giriş"),
    ("girisi", "girişi"),
    ("girilen", "girilen"),
    ("girin", "girin"),
    ("etkinlestir", "etkinleştir"),
    ("etkinlestirme", "etkinleştirme"),
    ("etkinlestirir", "etkinleştirir"),
    ("etkinlestirmek", "etkinleştirmek"),
    ("etkin", "etkin"),
    ("oyuncu", "oyuncu"),
    ("oyuncular", "oyuncular"),
    ("oyuncularin", "oyuncuların"),
    ("oyunu", "oyunu"),
    ("oyunun", "oyunun"),
    ("oyunudur", "oyunudur"),
    ("oynanis", "oynanış"),
    ("oynanisi", "oynanışı"),
    ("sunucuya", "sunucuya"),
    ("sunucunun", "sunucunun"),
    ("sunucunuzda", "sunucunuzda"),
    ("sunuculari", "sunucuları"),
    ("sunucularini", "sunucularını"),
    ("sunucusu", "sunucusu"),
    ("sunucudur", "sunucudur"),
    ("sunucusudur", "sunucusudur"),
    ("istegi", "isteği"),
    ("istediginiz", "istediğiniz"),
    ("isteginize", "isteğinize"),
    ("yapmak", "yapmak"),
    ("yapmasi", "yapması"),
    ("yapmaya", "yapmaya"),
    ("saglamak", "sağlamak"),
    ("saglar", "sağlar"),
    ("saglandi", "sağlandı"),
    ("saglayan", "sağlayan"),
    ("saglamakta", "sağlamakta"),
    ("sadece", "sadece"),
    ("bagli", "bağlı"),
    ("baglidir", "bağlıdır"),
    ("yukleyecektir", "yükleyecektir"),
    ("yuklendikten", "yüklendikten"),
    ("yuklenir", "yüklenir"),
    ("yuklemek", "yüklemek"),
    ("yuklemeyi", "yüklemeyi"),
    ("yuklenebilir", "yüklenebilir"),
    ("bulunur", "bulunur"),
    ("bulunmaktadir", "bulunmaktadır"),
    ("bulunmamaktadir", "bulunmamaktadır"),
    ("yazilmis", "yazılmış"),
    ("yazilmistir", "yazılmıştır"),
    ("oldugunca", "olduğunca"),
    ("oldugu", "olduğu"),
    ("oldukca", "oldukça"),
    ("olusturma", "oluşturma"),
    ("olusturmak", "oluşturmak"),
    ("olusturur", "oluşturur"),
    ("olusturulan", "oluşturulan"),
    ("olusumu", "oluşumu"),
    ("olusumunu", "oluşumunu"),
    ("eklenti", "eklenti"),
    ("eklentileri", "eklentileri"),
    ("eklentiler", "eklentiler"),
    ("eklentisini", "eklentisini"),
    ("eklentisi", "eklentisi"),
    ("yukleyici", "yükleyici"),
    ("yukleyicisi", "yükleyicisi"),
    ("yukleyicisidir", "yükleyicisidir"),
    ("dosya", "dosya"),
    ("dosyasi", "dosyası"),
    ("dosyasini", "dosyasını"),
    ("dosyalari", "dosyaları"),
    ("dosyalarini", "dosyalarını"),
    ("klasor", "klasör"),
    ("klasoru", "klasörü"),
    ("depoyu", "depoyu"),
    ("deposu", "deposu"),
    ("deposunu", "deposunu"),
    ("depolanan", "depolanan"),
    ("depoladigi", "depoladığı"),
    ("paneli", "paneli"),
    ("panelini", "panelini"),
    ("panelinde", "panelinde"),
    ("panelindeki", "panelindeki"),
    ("portu", "portu"),
    ("portundan", "portundan"),
    ("portuna", "portuna"),
    ("senaryo", "senaryo"),
    ("senaryolar", "senaryolar"),
    ("senaryolari", "senaryoları"),
    ("senaryolarinizi", "senaryolarınızı"),
    ("senaryosu", "senaryosu"),
    ("gorev", "görev"),
    ("gorevleri", "görevleri"),
    ("gore", "göre"),
    ("anahtarlarinizi", "anahtarlarınızı"),
    ("anahtarinizi", "anahtarınızı"),
    ("anahtari", "anahtarı"),
    ("alin", "alın"),
    ("ayarlayin", "ayarlayın"),
    ("sirasinda", "sırasında"),
    ("kaynaklarini", "kaynaklarını"),
    ("aciksa", "açıksa"),
    ("sayilir", "sayılır"),
    ("kismindan", "kısmından"),
    ("tusuna", "tuşuna"),
    ("basmak", "basmak"),
    ("olani", "olanı"),
    ("tutarsizliklarini", "tutarsızlıklarını"),
    ("duzeltmeyi", "düzeltmeyi"),
    ("amaclayan", "amaçlayan"),
    ("catallanmasi", "çatallanması"),
    ("catallanmasidir", "çatallanmasıdır"),
    ("performansli", "performanslı"),
    ("performansi", "performansı"),
    ("performansini", "performansını"),
    ("modlanmis", "modlanmış"),
    ("odullu", "ödüllü"),
    ("takim", "takım"),
    ("aksiyonunu", "aksiyonunu"),
    ("birlestiriyor", "birleştiriyor"),
    ("cagir", "çağır"),
    ("acan", "açan"),
    ("tasarlandi", "tasarlandı"),
    ("kullanilmak", "kullanılmak"),
    ("uzerine", "üzerine"),
    ("donanim", "donanım"),
    ("donanimi", "donanımı"),
    ("yazilim", "yazılım"),
    ("yazilimi", "yazılımı"),
    ("yazilimdir", "yazılımdır"),
    ("islemci", "işlemci"),
    ("isletim", "işletim"),
    ("sistemi", "sistemi"),
    ("sistemidir", "sistemidir"),
    ("sistemine", "sistemine"),
    ("sisteminde", "sisteminde"),
    ("sistemini", "sistemini"),

    # --- DAHA FAZLA ÇEKİMLİ FORM ---
    ("oyuncuya", "oyuncuya"),
    ("oyuncudan", "oyuncudan"),
    ("oyuncularla", "oyuncularla"),
    ("maksimuma", "maksimuma"),
    ("sayisinda", "sayısında"),
    ("sayisindan", "sayısından"),
    ("oynamak", "oynamak"),
    ("oynayin", "oynayın"),
    ("oynanabilir", "oynanabilir"),
    ("oynayan", "oynayan"),
    ("oynarken", "oynarken"),
    ("calistirmak", "çalıştırmak"),
    ("calistirilir", "çalıştırılır"),
    ("calistirir", "çalıştırır"),
    ("calismak", "çalışmak"),
    ("calismasi", "çalışması"),
    ("calisacak", "çalışacak"),
    ("calisacaktir", "çalışacaktır"),
    ("kurulumda", "kurulumda"),
    ("kurulumdan", "kurulumdan"),
    ("kurulumu", "kurulumu"),
    ("kurulumuna", "kurulumuna"),
    ("kurulumunda", "kurulumunda"),
    ("guncellemek", "güncellemek"),
    ("guncelleyin", "güncelleyin"),
    ("guncellenir", "güncellenir"),
    ("guncellenen", "güncellenen"),
    ("guncellenerek", "güncellenerek"),
    ("guncellemesini", "güncellemesini"),
    ("guncellemesidir", "güncellemesidir"),
    ("silinir", "silinir"),
    ("silin", "silin"),
    ("silinecek", "silinecek"),
    ("silinecektir", "silinecektir"),
    ("alinabilir", "alınabilir"),
    ("alinir", "alınır"),
    ("alinmasi", "alınması"),
    ("belirler", "belirler"),
    ("belirlemek", "belirlemek"),
    ("belirlenir", "belirlenir"),
    ("belirleme", "belirleme"),
    ("girilmelidir", "girilmelidir"),
    ("girilmelidir", "girilmelidir"),
    ("girilmesi", "girilmesi"),
    ("girildiginde", "girildiğinde"),
    ("girisi", "girişi"),
    ("saglamaktadir", "sağlamaktadır"),
    ("saglandiktan", "sağlandıktan"),
    ("saglandiginda", "sağlandığında"),
    ("kesfetme", "keşfetme"),
    ("kesfetmek", "keşfetmek"),
    ("kesfeder", "keşfeder"),
    ("kesfederek", "keşfederek"),
    ("kesfedilebilir", "keşfedilebilir"),
    ("kesfedildi", "keşfedildi"),
    ("insaet", "inşaet"),
    ("insaetme", "inşaetme"),
    ("insaedin", "inşaedin"),
    ("dogmasina", "doğmasına"),
    ("dogdugunda", "doğduğunda"),
    ("dogar", "doğar"),
    ("girisinde", "girişinde"),
    ("girisindeki", "girişindeki"),
    ("cikis", "çıkış"),
    ("cikisi", "çıkışı"),
    ("cikista", "çıkışta"),
    ("dagilimi", "dağılımı"),
    ("dagilimini", "dağılımını"),
    ("dagitimi", "dağıtımı"),
    ("etkilesim", "etkileşim"),
    ("etkilesimli", "etkileşimli"),
    ("gelisme", "gelişme"),
    ("gelismislik", "gelişmişlik"),
    ("gelistirilmesi", "geliştirilmesi"),
    ("gelistirilmesini", "geliştirilmesini"),
    ("gelistiricisi", "geliştiricisi"),
    ("gelistiricisidir", "geliştiricisidir"),
    ("kullanilabilirlik", "kullanılabilirlik"),
    ("yonetmek", "yönetmek"),
    ("yonetimi", "yönetimi"),
    ("yonetimini", "yönetimini"),
    ("yoneticisi", "yöneticisi"),
    ("yonetir", "yönetir"),
    ("yonlendirir", "yönlendirir"),
    ("yonlendirme", "yönlendirme"),
    ("yonlendirmesi", "yönlendirmesi"),
    ("dogrulandi", "doğrulandı"),
    ("dogrulanmasi", "doğrulanması"),
    ("dogrulayin", "doğrulayın"),
    ("dogrular", "doğrular"),
    ("eklenmistir", "eklenmiştir"),
    ("eklenebilir", "eklenebilir"),
    ("eklenir", "eklenir"),
    ("ozellestirme", "özelleştirme"),
    ("ozellestirilebilir", "özelleştirilebilir"),
    ("ozellestirilmis", "özelleştirilmiş"),
    ("yapilandirilmasi", "yapılandırılması"),
    ("yapilandirilir", "yapılandırılır"),

    # --- DAHA FAZLA İSİM ---
    ("deneyim", "deneyim"),
    ("deneyimi", "deneyimi"),
    ("deneyimini", "deneyimini"),
    ("macerasi", "macera"),
    ("maceraya", "macera"),
    ("macerada", "macerada"),
    ("gezegeni", "gezegen"),
    ("gezegende", "gezegen"),
    ("gezegenin", "gezegen"),
    ("evreni", "evren"),
    ("evrende", "evren"),
    ("evrenin", "evren"),
    ("haritasi", "harita"),
    ("haritasini", "harita"),
    ("haritasinda", "harita"),
    ("haritada", "harita"),
    ("silahlar", "silahlar"),
    ("silahlari", "silahları"),
    ("silahlarla", "silahlarla"),
    ("dusmanlar", "düşmanlar"),
    ("dusmanlari", "düşmanları"),
    ("dusmanlarla", "düşmanlarla"),
    ("canavarlar", "canavarlar"),
    ("canavarlari", "canavarları"),
    ("canavarlarla", "canavarlarla"),
    ("zombiler", "zombiler"),
    ("zombileri", "zombileri"),
    ("zombilerle", "zombilerle"),
    ("yaratiklar", "yaratıklar"),
    ("yaratiklari", "yaratıkları"),
    ("hayvanlar", "hayvanlar"),
    ("hayvanlari", "hayvanları"),
    ("bloklari", "blokları"),
    ("bloklarla", "bloklarla"),
    ("bloklarini", "bloklarını"),
    ("esyalar", "eşyalar"),
    ("esyalari", "eşyaları"),
    ("esyalarla", "eşyalarla"),
    ("esyalarin", "eşyaların"),
    ("kaynaklar", "kaynaklar"),
    ("kaynaklari", "kaynakları"),
    ("kaynaklarla", "kaynaklarla"),
    ("zindanlar", "zindanlar"),
    ("zindanlari", "zindanları"),
    ("zindanlarda", "zindanlarda"),
    ("yapilar", "yapılar"),
    ("yapilari", "yapıları"),
    ("yapilarla", "yapılarla"),
    ("barinaklar", "barınaklar"),
    ("barinaklari", "barınakları"),
    ("bolgeler", "bölgeler"),
    ("bolgeleri", "bölgeleri"),
    ("bolgelere", "bölgelere"),
    ("bolgelerde", "bölgelerde"),
    ("teknolojiler", "teknolojiler"),
    ("teknolojileri", "teknolojileri"),
    ("teknolojisi", "teknolojisi"),
    ("teknolojisini", "teknolojisini"),
    ("teknolojisiyle", "teknolojisiyle"),
    ("modifikasyon", "modifikasyon"),
    ("modifikasyonlar", "modifikasyonlar"),
    ("optimizasyon", "optimizasyon"),
    ("optimizasyonu", "optimizasyonu"),
    ("optimizasyonlar", "optimizasyonlar"),
    ("stabilite", "stabilite"),
    ("stabilitesi", "stabilitesi"),
    ("guvenlik", "güvenlik"),
    ("guvenligi", "güvenliği"),
    ("guvenligini", "güvenliğini"),
    ("performans", "performans"),
    ("topluluk", "topluluk"),
    ("toplulugu", "topluluğu"),
    ("toplulukla", "toplulukla"),
    ("topluluklar", "topluluklar"),
    ("toplulukta", "toplulukta"),
    ("ozelliklerine", "özelliklerine"),
    ("ozelliklerini", "özelliklerini"),
    ("ozellikleriyle", "özellikleriyle"),
    ("ozelligi", "özelliği"),
    ("ozelligini", "özelliğini"),
    ("ozelligidir", "özelliğidir"),
    ("kabiliyeti", "kabiliyeti"),
    ("kabiliyetine", "kabiliyetine"),
    ("yetkilerine", "yetkilerine"),
    ("yetkisi", "yetkisi"),
    ("yetkisini", "yetkisini"),
    ("ulasmak", "ulaşmak"),
    ("ulasir", "ulaşır"),
    ("ulasilabilir", "ulaşılabilir"),
    ("ulasimi", "ulaşımı"),
    ("ulasimini", "ulaşımını"),
    ("basladi", "başladı"),
    ("baslar", "başlar"),
    ("baslamadan", "başlamadan"),
    ("baslamasi", "başlaması"),
    ("baslamak", "başlamak"),
    ("basliyor", "başlıyor"),
    ("bitirmek", "bitirmek"),
    ("biter", "biter"),
    ("bittiginde", "bittiğinde"),
    ("gecme", "geçme"),
    ("gecmek", "geçmek"),
    ("gecis", "geçiş"),
    ("gecisi", "geçişi"),
    ("dogar", "doğar"),
    ("olusan", "oluşan"),
    ("olusur", "oluşur"),
    ("olusmasi", "oluşması"),
    ("olusmasini", "oluşmasını"),
    ("gelistirilirken", "geliştirilirken"),
    ("gelistirilmeye", "geliştirilmeye"),
    ("gelistiricileri", "geliştiricileri"),
    ("gelistiriciler", "geliştiriciler"),
    ("gelistiricilerin", "geliştiricilerin"),
    ("gelistiricilere", "geliştiricilere"),
    ("tarafindan", "tarafından"),
    ("tarafindandir", "tarafındandır"),
    ("saglandiginda", "sağlandığında"),
    ("saglandiktan", "sağlandıktan"),
    ("yapabildiginiz", "yapabildiğiniz"),
    ("yapabileceginiz", "yapabileceğiniz"),
    ("yapilmistir", "yapılmıştır"),
    ("yapilabilir", "yapılabilir"),
    ("yapilmalidir", "yapılmalıdır"),
    ("yapilmasi", "yapılması"),
    ("yapilandirmak", "yapılandırmak"),
    ("yapilandirmaniza", "yapılandırmanıza"),
    ("yukleyebilirsiniz", "yükleyebilirsiniz"),
    ("yuklenebilir", "yüklenebilir"),
    ("yuklenmesi", "yüklenmesi"),
    ("yuklenmistir", "yüklenmiştir"),
    ("kurabilirsiniz", "kurabilirsiniz"),
    ("kurulmustur", "kurulmuştur"),
    ("kurulabilir", "kurulabilir"),
    ("kurmak", "kurmak"),
    ("kurmaya", "kurmaya"),
    ("kurmakla", "kurmakla"),
    ("barindirir", "barındırır"),
    ("barindiran", "barındıran"),
    ("barindirmasi", "barındırması"),
    ("karsilamak", "karşılamak"),
    ("karsilar", "karşılar"),
    ("karsilasacak", "karşılaşacak"),
    ("basa", "başa"),
    ("bas", "baş"),
    ("basarmak", "başarmak"),
    ("basari", "başarı"),
    ("basarili", "başarılı"),
    ("basit", "basit"),
    ("basittir", "basittir"),
    ("basitligi", "basitliği"),
    ("basittir", "basittir"),
    ("hizmet", "hizmet"),
    ("hizmeti", "hizmeti"),
    ("hizmetini", "hizmetini"),
    ("hizmetidir", "hizmetidir"),
    ("tabanli", "tabanlı"),
    ("tabanlidir", "tabanlıdır"),
    ("tabanina", "tabanına"),
    ("odakli", "odaklı"),
    ("odaklidir", "odaklıdır"),
    ("odaklanarak", "odaklanarak"),
    ("dogruca", "doğruca"),
    ("dogrudur", "doğrudur"),
    ("saglandigina", "sağlandığına"),
    ("sahiptir", "sahiptir"),
    ("sahiptirler", "sahiptirler"),
    ("cogaltma", "çoğaltma"),
    ("cogalmasi", "çoğalması"),
    ("cogalir", "çoğalır"),
    ("paylasmak", "paylaşmak"),
    ("paylasimi", "paylaşımı"),
    ("paylasimini", "paylaşımını"),
    ("paylasabilir", "paylaşabilir"),
    ("karsilastirma", "karşılaştırma"),
    ("karsilastirir", "karşılaştırır"),
    ("karsilastirildiginda", "karşılaştırıldığında"),
    ("basarisiz", "başarısız"),
    ("basarisizlik", "başarısızlık"),
    ("dogruluk", "doğruluk"),
    ("dogrulugunu", "doğruluğunu"),
    ("yanlis", "yanlış"),
    ("yanlislikla", "yanlışlıkla"),
    ("durumda", "durumda"),
    ("durumunda", "durumunda"),
    ("durumlarda", "durumlarda"),
    ("durumudur", "durumudur"),
    ("durumunu", "durumunu"),
    ("durumuna", "durumuna"),
    ("sebep", "sebep"),
    ("sebebi", "sebebi"),
    ("sebebiyle", "sebebiyle"),
    ("sebeple", "sebeple"),
    ("amac", "amaç"),
    ("amaci", "amacı"),
    ("amacini", "amacını"),
    ("amaciyla", "amacıyla"),
    ("amaciyla", "amacıyla"),
    ("amaclamaktadir", "amaçlamaktadır"),
    ("hedef", "hedef"),
    ("hedefi", "hedefi"),
    ("hedefini", "hedefini"),
    ("hedefidir", "hedefidir"),
    ("sonucu", "sonucu"),
    ("sonucunda", "sonucunda"),
    ("sonucudur", "sonucudur"),
    ("sonucunu", "sonucunu"),
    ("neticesinde", "neticesinde"),
    # --- SON TARAMADA BULUNAN EKSİK KELİMELER ---
    ("isbirligi", "işbirliği"),
    ("guncellenmesi", "güncellenmesi"),
    ("sonrasinda", "sonrasında"),
    ("geldigi", "geldiği"),
    ("sunmayi", "sunmayı"),
    ("uygulamasi", "uygulaması"),
    ("olusturmayi", "oluşturmayı"),
    ("kullanilacak", "kullanılacak"),
    ("kullanilarak", "kullanılarak"),
    ("kolayligi", "kolaylığı"),
    ("kaldirarak", "kaldırarak"),
    ("yoneticiligi", "yöneticiliği"),
    ("uzerindeki", "üzerindeki"),
    ("dusunulerek", "düşünülerek"),
    ("sayfasina", "sayfasına"),
    ("hayranligi", "hayranlığı"),
    ("atesleyecek", "ateşleyecek"),
    ("kolonilestirilmeye", "kolonileştirilmeye"),
    ("baglanacak", "bağlanacak"),
    ("islenecek", "işlenecek"),
    ("dijitallestirilecek", "dijitalleştirilecek"),
    ("uretilecek", "üretilecek"),
    ("birlestirilecek", "birleştirilecek"),
    ("bayilacak", "bayılacak"),
    ("kesfedecek", "keşfedecek"),
    ("cikaracak", "çıkaracak"),
    ("hakkindaki", "hakkındaki"),
    ("kalmasina", "kalmasına"),
    ("kazasindan", "kazasından"),
    ("kurdugu", "kurduğu"),
    ("adasindaki", "adasındaki"),
    ("olmamasi", "olmaması"),
    ("oynanis", "oynanış"),
    ("oynanisi", "oynanışı"),
    ("tarayicisinda", "tarayıcısında"),
    ("tarayicisindaki", "tarayıcısındaki"),
    ("indirilecek", "indirilecek"),
    ("guncellenen", "güncellenen"),
    ("guncelleyen", "güncelleyen"),
    ("sunucunuzdaki", "sunucunuzdaki"),
    ("sunucudaki", "sunucudaki"),
    ("ayarlanacak", "ayarlanacak"),
    ("etmeye", "etmeye"),
)

# ============================================================================
# İNGİLİZCE PARÇALARI DÜZELTME
# ============================================================================

DESC_FRAGMENT_FIXES = [
    ("Required to start the service.", "Hizmeti başlatmak için gereklidir."),
    ("adi.jar dosyasi to run sunucu with.", "Sunucu jar dosyası."),
    ("adi.jarfile to run the server with.", "Sunucu jar dosyası."),
    ("Sunucunun adi.jarfile to run the server with.", "Sunucu jar dosyası."),
    ("(default is off)", "(varsayılan: kapalı)"),
    ("Read docs for possible values:", "Olası değerler için dökümantasyona bakın:"),
    ("The description that shows up in the server browser.", "Sunucu tarayıcısında görünen açıklama."),
    ("Use sending range only.", "Yalnızca gönderim aralığını kullanır."),
    ("Specifies the maximum amount of players that are able to join the server.", "Sunucuya katılabilecek maksimum oyuncu sayısını belirler."),
    ("This is to Etkinlestir / Devre Disi Birak auto-updating your server on restart.", "Yeniden başlatmada sunucunun otomatik güncellenmesini etkinleştirir veya devre dışı bırakır."),
    ("By default this is set to enabled.", "Varsayılan olarak bu etkindir."),
    ("Etkinlestir / Devre Disi Birak VAC (Valve Anti Cheat) on your server. By default this will be enabled.", "Sunucunuzda VAC'i (Valve Anti Cheat) etkinleştirin veya devre dışı bırakın. Varsayılan olarak bu etkindir."),
    ("Etkinlestir / Devre Disi Birak RCON for using RCON commands with external tools. By default this will be disabled.", "Harici araçlarla RCON komutlarını kullanmak için RCON'u etkinleştirin veya devre dışı bırakın. Varsayılan olarak bu devre dışıdır."),
    ("Sets the server name listed in the steam server browser.", "Steam sunucu tarayıcısında listelenen sunucu adını belirler."),
    ("To gain access to administrator commands on the server.", "Sunucudaki yönetici komutlarına erişmek için."),
    ("SourceTV port used for connections to spectates games on your server.", "Sunucunuzdaki oyunları izlemek için kullanılan SourceTV portu."),
    ("The token can be acquired here:", "Anahtar şu adresten alınabilir:"),
    ("Defines the Gamemode and Gametype to be set at the start of the next round.", "Bir sonraki raundun başlangıcında ayarlanacak Oyun Modu ve Oyun Tipini tanımlar."),
    ("The port for the txAdmin panel.", "txAdmin paneli için port."),
    ("Enables txAdmin.", "txAdmin'i etkinleştirir."),
    ("The location txAdmin stores data.", "txAdmin'in verileri depoladığı konum."),
    ("Restricts to only running either FiveM or RedM servers.", "Yalnızca FiveM veya RedM sunucularını çalıştırmakla sınırlar."),
    ("Sets the sv_enforceGameBuild convar. This specifies the client GTA build the server should be on.", "sv_enforceGameBuild convar'ını ayarlar. Sunucunun kullanması gereken istemci GTA derlemesini belirtir."),
    ("The setup page will only show recipes for the game specified below!", "Kurulum sayfası yalnızca aşağıda belirtilen oyun için tarifler gösterir!"),
    ("Options are: fivem or redm", "Seçenekler: fivem veya redm"),
    ("The username used to authenticate with git.", "Git ile kimlik doğrulamak için kullanılan kullanıcı adı."),
    ("The password used to authenticate with git.", "Git ile kimlik doğrulamak için kullanılan şifre."),
    ("It's best practice to use a Personal Access Token.", "Kişisel Erişim Anahtarı kullanmak en iyi uygulamadır."),
    ("URL to Git repository.", "Git deposunun URL'si."),
    ("The name of the branch you wish to use. The default will be used if this is not specified.", "Kullanmak istediğiniz dalın adı. Belirtilmezse varsayılan dal kullanılır."),
    ("Sets the maximum player count.", "Maksimum oyuncu sayısını belirler."),
    ("The name that shows up when selecting the server in the server browser.", "Sunucu tarayıcısında sunucu seçilirken görünen ad."),
    ("The name that shows up in the server browser.", "Sunucu tarayıcısında görünen ad."),
    ("Use your Steam WebApiKey or set to 'none'.", "Steam WebApiKey'inizi kullanın veya 'none' olarak ayarlayın."),
    ("Get your key at", "Anahtarınızı şu adresten alın:"),
    ("Get your keys at", "Anahtarlarınızı şu adresten alın:"),
    ("FXServer artifact.", "FXServer artifact'ini indirir."),
    ("Or specify a direct version to download like", "Veya indirmek için doğrudan bir sürüm belirtin, örneğin"),
    ("Pressing 'Reinstall Server' in 'Settings' will remove the currently installed", "'Ayarlar' kısmından 'Sunucuyu Yeniden Kur' tuşuna basmak şu anda yüklü olanı kaldırır"),
    ("Can be set to 'latest', 'recommended', or a specific version.", "'latest', 'recommended' veya belirli bir sürüm olarak ayarlanabilir."),
    ("You can find the latest version from here -", "En son sürümü buradan bulabilirsiniz -"),
    ("The Steam Account Token required for the server to be displayed public.", "Sunucunun herkese açık görüntülenmesi için gereken Steam Hesap Anahtarı."),
    ("Downloads the latest or specified FiveM/RedM FXServer artifact.", "En son veya belirtilen FiveM/RedM FXServer artifact'ini indirir."),
    ("Enable or disable 3d audio. Does nothing if 'UseNativeAudio' is set to true.", "3D sesi etkinleştirir veya devre dışı bırakır. 'UseNativeAudio' true ise etkisizdir."),
    ("Enable or disable Native audio. You should be using this for the best possible VOIP. Greatly superior to 'Use3dAudio'.", "Yerel sesi etkinleştirir veya devre dışı bırakır. En iyi VOIP deneyimi için bunu kullanmalısınız. 'Use3dAudio'dan çok daha üstündür."),
    ("Set to 'on' to enable Onesync. Set to 'off' if you want to disable Onesync. Optionally you can use 'legacy' however it is strongly advised against. If you are running a server you should have Onesync enabled.", "Onesync'i etkinleştirmek için 'on', devre dışı bırakmak için 'off' yapın. Alternatif olarak 'legacy' kullanılabilir ancak önerilmez. Bir sunucu çalıştırıyorsanız Onesync etkin olmalıdır."),
    ("Enabling this will clone or pull the specified repository into /resources on each server startup. If you are installing the server now, this will clone the git repo.", "Bunu etkinleştirmek, her sunucu başlangıcında belirtilen depoyu /resources dizinine klonlar veya çeker. Sunucuyu şimdi kuruyorsanız, git deposunu klonlar."),
]

# ============================================================================
# NORMALİZASYON FONKSİYONLARI
# ============================================================================

def normalize_turkish(text):
    """ASCII-Türkçe metni düzgün Türkçe Unicode'a çevirir."""
    if not text:
        return text

    # 1. Büyük harf bileşik ifadeleri eşle (uzundan kısaya)
    sorted_keys = sorted(TR_WORD_MAP.keys(), key=len, reverse=True)
    for key in sorted_keys:
        if key in text:
            text = text.replace(key, TR_WORD_MAP[key])

    # 2. Küçük harf kelimeleri eşle (kelime sınırı bazlı, en uzundan kısaya)
    sorted_lower = sorted(LOWER_MAP.keys(), key=len, reverse=True)
    for _ in range(2):  # İki geçiş: yan yana ASCII-Türkçe kelimeler için
        for old in sorted_lower:
            new = LOWER_MAP[old]
            pattern = re.compile(r'(?<![a-zA-ZğĞüÜşŞıİöÖçÇ])' + re.escape(old) + r'(?![a-zA-ZğĞüÜşŞıİöÖçÇ])', re.IGNORECASE)
            text = pattern.sub(new, text)

    return text


def fix_description_fragments(desc):
    """Açıklamalardaki İngilizce kalıntılarını düzelt."""
    if not desc:
        return desc

    for old, new in DESC_FRAGMENT_FIXES:
        if old in desc:
            desc = desc.replace(old, new)

    return desc


def process_file(filepath):
    """Tek bir JSON dosyasını işle."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    changed = False

    # Üst seviye açıklama
    if 'description' in data:
        new_desc = normalize_turkish(data['description'])
        new_desc = fix_description_fragments(new_desc)
        if new_desc != data['description']:
            data['description'] = new_desc
            changed = True

    # Değişken isimleri ve açıklamaları
    if 'variables' in data:
        for var in data['variables']:
            if 'name' in var:
                new_name = normalize_turkish(var['name'])
                if new_name != var['name']:
                    var['name'] = new_name
                    changed = True
            if 'description' in var:
                new_desc = normalize_turkish(var['description'])
                new_desc = fix_description_fragments(new_desc)
                if new_desc != var['description']:
                    var['description'] = new_desc
                    changed = True

    if changed:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

    return changed


def main():
    root = 'C:/Users/burak/Desktop/VEHOZER/EGGS/translated_eggs'
    total = 0
    changed = 0

    for dirpath, dirnames, filenames in os.walk(root):
        for fn in sorted(filenames):
            if fn.endswith('.json'):
                total += 1
                filepath = os.path.join(dirpath, fn)
                if process_file(filepath):
                    changed += 1
                    print(f"  Fixed: {os.path.relpath(filepath, root)}")

    print(f"\nTotal files: {total}, Fixed: {changed}")


if __name__ == '__main__':
    main()
